#!/usr/bin/env python3
"""Generates src/html/NamedCharacterReferences.inc from the HTML Standard's entity table.

The table is 2,231 named character references and it is *data*: the spec ships it as
`entities.json`, every browser embeds a copy, and it does not change. `src/html/Tokenizer.cpp`
carried a hand-written subset of 42 for a long time, with a comment saying the rest was "a data
change to grow it" -- this is that change, done the way `tools/unicode/generate.py` does its own:
a generator that reads the pinned data and writes a header, both checked in, so a reader can see
where every byte came from without running anything.

The source is the copy already in the web-platform-tests checkout
(`html/the-xhtml-syntax/parsing-xhtml-documents/support/entities.json`), which is the file the
suite's own XHTML entity tests are written against. Reading it from there rather than fetching it
means the table this browser expands and the table the tests check are provably the same bytes.

    tools/html/generate_entities.py

Run it after `tools/wpt/fetch.sh`, and commit the result.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SOURCE = os.path.join(
    ROOT, "third_party", "wpt", "html", "the-xhtml-syntax",
    "parsing-xhtml-documents", "support", "entities.json")
OUTPUT = os.path.join(ROOT, "src", "html", "NamedCharacterReferences.inc")


def c_string(text: str) -> str:
    """A C++ string literal of `text`'s UTF-8 bytes, escaped one byte at a time.

    Every byte is written as `\\xNN` rather than left as itself: a literal that mixed readable
    characters with escapes can end an escape early ("\\xA" followed by "b" is one byte, not two),
    which is the kind of bug that produces one wrong character in one entity and nothing else.
    """
    return "".join("\\x%02X" % byte for byte in text.encode("utf-8"))


def main() -> int:
    if not os.path.exists(SOURCE):
        sys.stderr.write("missing %s; run tools/wpt/fetch.sh first\n" % SOURCE)
        return 1
    with open(SOURCE, "r", encoding="utf-8") as handle:
        table = json.load(handle)

    # Keyed without the leading `&`, because that is what the tokenizer has consumed by the time it
    # looks one up. Sorted, so the generated array can be bucketed by first byte.
    entries = sorted((name[1:], value["characters"]) for name, value in table.items())
    if not entries:
        sys.stderr.write("entities.json parsed to nothing\n")
        return 1

    longest = max(len(name) for name, _ in entries)
    buckets = {}
    for index, (name, _) in enumerate(entries):
        buckets.setdefault(name[0], [index, index])[1] = index

    lines = []
    lines.append("// Generated by tools/html/generate_entities.py from the HTML Standard's entity table.")
    lines.append("// DO NOT EDIT. Regenerate instead, and diff the result.")
    lines.append("//")
    lines.append("// The HTML Standard's named character references, all %d of them, from the copy"
                 % len(entries))
    lines.append("// of `entities.json` in the web-platform-tests checkout -- which is the same file")
    lines.append("// the suite's own entity tests are written against, so the table this browser")
    lines.append("// expands and the table the tests check are provably the same bytes.")
    lines.append("//")
    lines.append("// Names are stored **without** the leading `&`, which the tokenizer has already")
    lines.append("// consumed, and *with* the trailing `;` where the reference has one. The ones")
    lines.append("// without it are the specification's historical list: `&copy` is a legal")
    lines.append("// reference and `&copyright` is `&copy` followed by `right`, which is why the")
    lines.append("// lookup is longest-match rather than read-until-semicolon.")
    lines.append("")
    lines.append("struct NamedCharacterReference {")
    lines.append("  std::string_view name;")
    lines.append("  std::string_view replacement;")
    lines.append("};")
    lines.append("")
    lines.append("// The longest name in the table, which bounds how far the tokenizer has to look")
    lines.append("// ahead after an `&`.")
    lines.append("constexpr std::size_t kLongestNamedCharacterReference = %d;" % longest)
    lines.append("")
    lines.append("constexpr std::array<NamedCharacterReference, %d>" % len(entries))
    lines.append("    kNamedCharacterReferences = {{")
    for name, replacement in entries:
        lines.append('    {"%s", "%s"},' % (name, c_string(replacement)))
    lines.append("}};")
    lines.append("")
    lines.append("// Where each first byte's run begins and ends, so a lookup scans one letter's")
    lines.append("// entries rather than all %d. The largest run is 168." % len(entries))
    lines.append("struct NamedCharacterReferenceBucket {")
    lines.append("  char first;")
    lines.append("  std::size_t begin;")
    lines.append("  std::size_t end;  // one past the last")
    lines.append("};")
    lines.append("")
    lines.append("constexpr std::array<NamedCharacterReferenceBucket, %d>" % len(buckets))
    lines.append("    kNamedCharacterReferenceBuckets = {{")
    for first in sorted(buckets):
        begin, last = buckets[first]
        lines.append("    {'%s', %d, %d}," % (first, begin, last + 1))
    lines.append("}};")
    lines.append("")

    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    sys.stderr.write("wrote %s: %d references, longest %d\n" % (OUTPUT, len(entries), longest))
    return 0


if __name__ == "__main__":
    sys.exit(main())
