#include <memory>
#include <string>
#include <string_view>
#include <vector>

#include "TestSupport.h"
#include "css/StyleResolver.h"
#include "css/StyleSheet.h"
#include "html/TreeBuilder.h"
#include <variant>

#include "gfx/DisplayList.h"
#include "layout/LayoutEngine.h"

// Flex layout.
//
// Every expectation here is a number, because that is the only way to tell a
// working flex container from one that merely stacked its children and
// happened to look right in a screenshot. Ten pixels per character at a 20px
// font, so a width is something a test can state.

namespace microbrowser::tests {

using layout::Box;
using layout::FixedTextMeasurer;
using layout::LayoutEngine;

namespace {

constexpr float kAdvance = 0.5f;

struct Flexed {
  std::unique_ptr<dom::Document> document;
  std::unique_ptr<css::StyleResolver> resolver;
  std::unique_ptr<FixedTextMeasurer> measurer;
  std::unique_ptr<Box> root;
  float height = 0.0f;
};

Flexed Run(std::string_view html, std::string_view css_text, float width = 400.0f) {
  Flexed result;
  result.document = html::ParseDocument(html);
  result.resolver = std::make_unique<css::StyleResolver>();
  result.resolver->AddStyleSheet(css::ParseStyleSheet(css_text), css::Origin::Author);
  result.measurer = std::make_unique<FixedTextMeasurer>(kAdvance);
  const LayoutEngine engine(*result.resolver, *result.measurer);
  result.root = engine.BuildBoxTree(*result.document);
  result.height = engine.Layout(*result.root, width);
  return result;
}

// Every box generated by an element with this tag, in tree order.
std::vector<const Box*> Items(const Box& root, std::string_view tag) {
  std::vector<const Box*> boxes;
  root.ForEachDescendant([&](const Box& box) {
    if (box.Origin() != nullptr && box.Origin()->TagName() == tag) {
      boxes.push_back(&box);
    }
  });
  return boxes;
}

// Every text box under `root`, in tree order.
std::vector<const Box*> TextBoxesIn(const Box& root) {
  std::vector<const Box*> boxes;
  root.ForEachDescendant([&](const Box& box) {
    if (box.GetKind() == Box::Kind::Text) {
      boxes.push_back(&box);
    }
  });
  return boxes;
}

// The items' content rectangles as "x,w" pairs, which is what nearly every
// expectation below is about. Rounded, because a distributed remainder is not
// a number a test should be pinned to the last bit of.
std::string Horizontal(const Box& root, std::string_view tag) {
  std::string out;
  for (const Box* box : Items(root, tag)) {
    if (!out.empty()) {
      out += " ";
    }
    out += std::to_string(static_cast<int>(box->Geometry().content.x + 0.5f)) + "," +
           std::to_string(static_cast<int>(box->Geometry().content.width + 0.5f));
  }
  return out;
}

std::string Vertical(const Box& root, std::string_view tag) {
  std::string out;
  for (const Box* box : Items(root, tag)) {
    if (!out.empty()) {
      out += " ";
    }
    out += std::to_string(static_cast<int>(box->Geometry().content.y + 0.5f)) + "," +
           std::to_string(static_cast<int>(box->Geometry().content.height + 0.5f));
  }
  return out;
}

// A container 300 wide with no margins anywhere, so the numbers in a test are
// the numbers flex layout produced and not a body margin.
constexpr const char* kReset =
    "body, div, span, p { margin: 0; padding: 0; border: 0; font-size: 20px } "
    ".flex { display: flex; width: 300px } ";

}  // namespace

void RegisterFlexLayoutTests(std::vector<TestCase>& tests) {
  AddTest(tests, "Flex/ItemsSitSideBySideRatherThanStacking", [] {
    // The whole point, and the thing a block container cannot do.
    const Flexed result = Run(
        "<div class=flex><p>ab</p><p>cd</p></div>",
        std::string(kReset) + "p { width: 50px }");
    ExpectEqString(Horizontal(*result.root, "p"), "0,50 50,50", "laid out along the row");
    // A 20px font makes a 24px line box, which is the height an item with one
    // line of text has.
    ExpectEqString(Vertical(*result.root, "p"), "0,24 0,24", "and at the same height");
  });

  AddTest(tests, "Flex/GrowSharesWhatIsLeftInProportion", [] {
    const Flexed result = Run(
        "<div class=flex><p id=a>a</p><p id=b>b</p></div>",
        std::string(kReset) + "p { flex-basis: 0 } #a { flex-grow: 1 } #b { flex-grow: 3 }");
    // 300 shared one-to-three.
    ExpectEqString(Horizontal(*result.root, "p"), "0,75 75,225", "in proportion to the factors");
  });

  AddTest(tests, "Flex/ShrinkIsWeightedByBaseSizeAndNotOnlyByFactor", [] {
    // The rule that keeps a long item from collapsing beside a short one: a
    // large item gives up more than a small one with the same factor. Bases of
    // 300 and 100 overflow by 100, so the first gives up 75 and the second 25.
    const Flexed result = Run(
        "<div class=flex><p id=a>a</p><p id=b>b</p></div>",
        std::string(kReset) + "#a { flex-basis: 300px } #b { flex-basis: 100px }");
    ExpectEqString(Horizontal(*result.root, "p"), "0,225 225,75", "shrunk in proportion");
  });

  AddTest(tests, "Flex/FlexOneMeansGrowShrinkAndAZeroBasis", [] {
    // `flex: 1` fills and `flex-grow: 1` does not, because the shorthand sets
    // the basis to zero and the longhand leaves it auto. Pages depend on the
    // difference and it is the most common flex mistake.
    const Flexed filled = Run("<div class=flex><p>aaaa</p><p>b</p></div>",
                              std::string(kReset) + "p { flex: 1 }");
    ExpectEqString(Horizontal(*filled.root, "p"), "0,150 150,150", "equal, whatever the content");

    const Flexed absorbed = Run("<div class=flex><p>aaaa</p><p>b</p></div>",
                                std::string(kReset) + "p { flex-grow: 1 }");
    // Content is 40 and 10 wide; the 250 left over is split evenly on top.
    ExpectEqString(Horizontal(*absorbed.root, "p"), "0,165 165,135",
                   "content size plus an equal share");
  });

  AddTest(tests, "Flex/JustifyContentPlacesTheLeftoverSpace", [] {
    const std::string markup = "<div class=flex><p>a</p><p>b</p></div>";
    const std::string base = std::string(kReset) + "p { width: 100px } .flex { ";
    // 300 wide, 200 used, 100 left over.
    ExpectEqString(Horizontal(*Run(markup, base + "justify-content: flex-start }").root, "p"),
                   "0,100 100,100", "start");
    ExpectEqString(Horizontal(*Run(markup, base + "justify-content: flex-end }").root, "p"),
                   "100,100 200,100", "end");
    ExpectEqString(Horizontal(*Run(markup, base + "justify-content: center }").root, "p"),
                   "50,100 150,100", "center");
    ExpectEqString(Horizontal(*Run(markup, base + "justify-content: space-between }").root, "p"),
                   "0,100 200,100", "space-between puts it all in the middle");
    // Half a gap at each end, so the outer spaces are half the inner one.
    ExpectEqString(Horizontal(*Run(markup, base + "justify-content: space-around }").root, "p"),
                   "25,100 175,100", "space-around");
    ExpectEqString(Horizontal(*Run(markup, base + "justify-content: space-evenly }").root, "p"),
                   "33,100 167,100", "space-evenly");
  });

  AddTest(tests, "Flex/AlignItemsPositionsAcrossTheLine", [] {
    const std::string markup =
        "<div class=flex><p id=tall>a</p><p id=short>b</p></div>";
    const std::string base =
        std::string(kReset) + "p { width: 100px } #tall { height: 100px } .flex { ";
    // The line is 100 tall because of the first item; the second is 20.
    ExpectEqString(Vertical(*Run(markup, base + "align-items: flex-start }").root, "p"),
                   "0,100 0,24", "start");
    ExpectEqString(Vertical(*Run(markup, base + "align-items: flex-end }").root, "p"),
                   "0,100 76,24", "end");
    ExpectEqString(Vertical(*Run(markup, base + "align-items: center }").root, "p"),
                   "0,100 38,24", "center");
    // Stretch is the default, and it is what makes a row of boxes with
    // different amounts of text end up the same height.
    ExpectEqString(Vertical(*Run(markup, base + "align-items: stretch }").root, "p"),
                   "0,100 0,100", "stretch");
  });

  AddTest(tests, "Flex/AlignSelfOverridesTheContainer", [] {
    const Flexed result = Run(
        "<div class=flex><p id=tall>a</p><p id=odd>b</p></div>",
        std::string(kReset) +
            "p { width: 100px } #tall { height: 100px } "
            ".flex { align-items: flex-start } #odd { align-self: flex-end }");
    ExpectEqString(Vertical(*result.root, "p"), "0,100 76,24", "one item, its own alignment");
  });

  AddTest(tests, "Flex/AColumnStacksAlongTheOtherAxis", [] {
    const Flexed result = Run(
        "<div class=flex><p>a</p><p>b</p></div>",
        std::string(kReset) + ".flex { flex-direction: column }");
    ExpectEqString(Vertical(*result.root, "p"), "0,24 24,24", "stacked down the main axis");
    // A column item stretches across the container, which is the cross axis
    // here -- the same rule as a row item stretching in height.
    ExpectEqString(Horizontal(*result.root, "p"), "0,300 0,300", "and fills it across");
  });

  AddTest(tests, "Flex/ReverseChangesWhereItemsGoAndNotWhatTheyAre", [] {
    const Flexed result = Run(
        "<div class=flex><p>a</p><p>b</p></div>",
        std::string(kReset) + "p { width: 100px } .flex { flex-direction: row-reverse }");
    // Reversing moves the main-start edge to the right, so the first item is
    // the rightmost and the 100 left over ends up on the *left*. Placing the
    // items backwards from the left edge instead would reverse their order and
    // put the free space on the wrong side -- which looks right until there is
    // any, and is the bug this test was written after finding.
    ExpectEqString(Horizontal(*result.root, "p"), "200,100 100,100",
                   "the first item sits at the right, and the gap is on the left");
  });

  AddTest(tests, "Flex/OrderReordersWithoutReparenting", [] {
    const Flexed result = Run(
        "<div class=flex><p id=a>a</p><p id=b>b</p></div>",
        std::string(kReset) + "p { width: 100px } #a { order: 2 } #b { order: 1 }");
    // `a` is still the first child and still the first box; it is drawn second.
    ExpectEqString(Horizontal(*result.root, "p"), "100,100 0,100", "b takes the first position");
  });

  AddTest(tests, "Flex/WrappingStartsANewLineWhenAnItemDoesNotFit", [] {
    const Flexed result = Run(
        "<div class=flex><p>a</p><p>b</p><p>c</p></div>",
        std::string(kReset) + "p { width: 120px; height: 30px } .flex { flex-wrap: wrap }");
    // Two fit on the first line, the third goes below it.
    ExpectEqString(Horizontal(*result.root, "p"), "0,120 120,120 0,120", "two, then one");
    ExpectEqString(Vertical(*result.root, "p"), "0,30 0,30 30,30", "the third on a second line");
  });

  AddTest(tests, "Flex/NoWrapOverflowsRatherThanBreaking", [] {
    // The default. Without shrink there is nowhere for the third to go, and it
    // overflows rather than starting a line -- which is what `nowrap` means.
    const Flexed result = Run(
        "<div class=flex><p>a</p><p>b</p><p>c</p></div>",
        std::string(kReset) + "p { width: 120px; flex-shrink: 0 }");
    ExpectEqString(Horizontal(*result.root, "p"), "0,120 120,120 240,120", "all on one line");
  });

  AddTest(tests, "Flex/GapsSitBetweenItemsAndNotAroundThem", [] {
    const Flexed result = Run(
        "<div class=flex><p>a</p><p>b</p></div>",
        std::string(kReset) + "p { flex: 1 } .flex { gap: 20px }");
    // 300 less one 20px gap, shared.
    ExpectEqString(Horizontal(*result.root, "p"), "0,140 160,140", "one gap, between the two");
  });

  AddTest(tests, "Flex/TextDirectlyInsideAContainerBecomesAnItem", [] {
    // A flex container has no lines of its own: a run of inline content is
    // wrapped in a box and becomes an item like any other. Without that, the
    // text would be laid out as if the container were a block.
    const Flexed result = Run(
        "<div class=flex>loose<p>a</p></div>",
        std::string(kReset) + "p { width: 100px }");
    const std::vector<const Box*> paragraphs = Items(*result.root, "p");
    Expect(paragraphs.size() == 1, "the paragraph is one item");
    Expect(paragraphs[0]->Geometry().content.x > 0.0f,
           "and it sits after the anonymous item holding the text");
  });

  AddTest(tests, "Flex/MinAndMaxBoundTheResolvedLength", [] {
    // Growing stops at `max-width`, which is what keeps a `flex: 1` column
    // from stretching a control across a wide window.
    const Flexed capped = Run(
        "<div class=flex><p id=a>a</p><p id=b>b</p></div>",
        std::string(kReset) + "p { flex: 1 } #a { max-width: 60px }");
    // And the ninety it could not take is handed to its sibling rather than
    // left as a gap -- which is what the freeze-and-redistribute loop is for.
    ExpectEqString(Horizontal(*capped.root, "p"), "0,60 60,240",
                   "the capped item stops growing and passes the rest on");

    // Shrinking stops at `min-width`, which is what stops a label collapsing.
    const Flexed floored = Run(
        "<div class=flex><p id=a>a</p><p id=b>b</p></div>",
        std::string(kReset) +
            "#a { flex-basis: 300px; min-width: 250px } #b { flex-basis: 100px }");
    // Bases of 300 and 100 overflow by 100. The first would give up 75, but
    // its floor stops it at 250 -- so it freezes having given up only 50, and
    // the other 50 comes off the second. The redistribution is why this is 50
    // and not 75.
    ExpectEqString(Horizontal(*floored.root, "p"), "0,250 250,50",
                   "the floored item stops shrinking and the rest comes off its sibling");
  });

  AddTest(tests, "Flex/AMinimumBeatsAMaximumWhenTheyContradict", [] {
    // The spec resolves the maximum first and then the minimum, so a page that
    // writes both means the minimum. Observable only when they contradict, and
    // silently wrong the other way round.
    const Flexed result = Run("<div class=flex><p>a</p></div>",
                              std::string(kReset) + "p { width: 10px; min-width: 200px; "
                                                    "max-width: 100px }");
    ExpectEqString(Horizontal(*result.root, "p"), "0,200", "the minimum wins");
  });

  AddTest(tests, "Flex/BoundsApplyToOrdinaryBlocksToo", [] {
    // Not a flex rule: the clamp is applied wherever a used width is decided,
    // so a plain block honours it as well.
    const Flexed result = Run("<div id=wide></div>",
                              "body, div { margin: 0 } #wide { max-width: 120px }");
    const std::vector<const Box*> blocks = Items(*result.root, "div");
    Expect(blocks.size() == 1, "one block");
    ExpectEqInt(static_cast<long long>(blocks[0]->Geometry().content.width + 0.5f), 120,
                "a block wider than its maximum is clamped");
  });

  // --- Positioning -----------------------------------------------------------

  AddTest(tests, "Position/RelativeMovesTheBoxAndNotItsSpace", [] {
    // The defining difference from absolute: the box is drawn somewhere else
    // and its siblings are laid out as though it had not moved.
    const Flexed result = Run(
        "<div id=a></div><div id=b></div>",
        "body, div { margin: 0 } div { height: 20px } "
        "#a { position: relative; left: 30px; top: 5px }");
    const std::vector<const Box*> blocks = Items(*result.root, "div");
    Expect(blocks.size() == 2, "two blocks");
    ExpectEqInt(static_cast<long long>(blocks[0]->Geometry().content.x + 0.5f), 30, "moved right");
    ExpectEqInt(static_cast<long long>(blocks[0]->Geometry().content.y + 0.5f), 5, "and down");
    ExpectEqInt(static_cast<long long>(blocks[1]->Geometry().content.y + 0.5f), 20,
                "and the next block sits where it would have anyway");
  });

  AddTest(tests, "Position/RelativePrefersLeftAndTopWhenBothEdgesAreGiven", [] {
    // The two are the same offset stated twice, and the spec picks the first
    // for a left-to-right page.
    const Flexed result = Run("<div id=a></div>",
                              "body, div { margin: 0 } div { height: 20px } "
                              "#a { position: relative; left: 10px; right: 40px }");
    ExpectEqInt(static_cast<long long>(Items(*result.root, "div")[0]->Geometry().content.x + 0.5f),
                10, "left wins");
  });

  AddTest(tests, "Position/AbsoluteTakesNoSpaceFromItsSiblings", [] {
    const Flexed result = Run(
        "<div id=a></div><div id=b></div>",
        "body, div { margin: 0 } div { height: 20px } "
        "#a { position: absolute; left: 10px; top: 100px }");
    const std::vector<const Box*> blocks = Items(*result.root, "div");
    ExpectEqInt(static_cast<long long>(blocks[0]->Geometry().content.x + 0.5f), 10, "placed");
    ExpectEqInt(static_cast<long long>(blocks[0]->Geometry().content.y + 0.5f), 100, "at its offsets");
    // The one that matters: the sibling moved up to the top, because the
    // absolute box is not in the flow at all.
    ExpectEqInt(static_cast<long long>(blocks[1]->Geometry().content.y + 0.5f), 0,
                "the sibling starts at the top");
  });

  AddTest(tests, "Position/APositionedAncestorIsTheContainingBlock", [] {
    // `position: relative` with no offsets is the idiomatic way to anchor a
    // child, and it works because a *static* ancestor is transparent to the
    // search while a positioned one is not.
    const Flexed anchored = Run(
        "<div id=outer><div id=mid><div id=inner></div></div></div>",
        "body, div { margin: 0 } #outer { margin-top: 50px; height: 200px; position: relative } "
        "#mid { height: 100px } "
        "#inner { position: absolute; left: 10px; top: 10px; width: 20px; height: 20px }");
    const Box* inner = nullptr;
    anchored.root->ForEachDescendant([&](const Box& box) {
      const std::string* id = box.Origin() == nullptr ? nullptr : box.Origin()->GetAttribute("id");
      if (id != nullptr && *id == "inner") {
        inner = &box;
      }
    });
    Expect(inner != nullptr, "the inner box exists");
    // Offset from #outer's padding box, which starts at y=50.
    ExpectEqInt(static_cast<long long>(inner->Geometry().content.y + 0.5f), 60,
                "measured from the positioned ancestor, not from the page");

    // Without the anchor, the same markup measures from the root instead.
    const Flexed loose = Run(
        "<div id=outer><div id=mid><div id=inner></div></div></div>",
        "body, div { margin: 0 } #outer { margin-top: 50px; height: 200px } "
        "#mid { height: 100px } "
        "#inner { position: absolute; left: 10px; top: 10px; width: 20px; height: 20px }");
    const Box* unanchored = nullptr;
    loose.root->ForEachDescendant([&](const Box& box) {
      const std::string* id = box.Origin() == nullptr ? nullptr : box.Origin()->GetAttribute("id");
      if (id != nullptr && *id == "inner") {
        unanchored = &box;
      }
    });
    Expect(unanchored != nullptr, "and so does the unanchored one");
    ExpectEqInt(static_cast<long long>(unanchored->Geometry().content.y + 0.5f), 10,
                "measured from the page");
  });

  AddTest(tests, "Position/TwoOffsetsOnAnAxisGiveTheBoxItsSize", [] {
    // What `left: 0; right: 0` means, and how an overlay is written.
    const Flexed result = Run(
        "<div id=box></div>",
        "body, div { margin: 0 } "
        "#box { position: absolute; left: 20px; right: 30px; height: 10px }");
    const Box* box = Items(*result.root, "div")[0];
    ExpectEqInt(static_cast<long long>(box->Geometry().content.x + 0.5f), 20, "left edge");
    // The viewport in these tests is 400 wide.
    ExpectEqInt(static_cast<long long>(box->Geometry().content.width + 0.5f), 350,
                "and the width is what is between the two offsets");
  });

  AddTest(tests, "Position/BottomPlacesTheBoxByItsLowerEdge", [] {
    // Which needs the height, so it is applied after the box has one rather
    // than guessed at.
    const Flexed result = Run(
        "<div id=box></div>",
        "body, div { margin: 0 } body { height: 200px } "
        "#box { position: absolute; bottom: 30px; left: 0; width: 10px; height: 20px }");
    const Box* box = Items(*result.root, "div")[0];
    const Box* root = result.root.get();
    const float page_bottom = root->Geometry().PaddingBox().Bottom();
    ExpectEqInt(static_cast<long long>(box->Geometry().content.y + 0.5f),
                static_cast<long long>(page_bottom - 30.0f - 20.0f + 0.5f),
                "its lower edge is thirty from the bottom");
  });

  AddTest(tests, "Position/OverflowClipsWhatDoesNotFit", [] {
    // The clip is the padding box -- the same rectangle a background paints --
    // so a clipped child stops exactly where the box's own paint stops.
    const Flexed result = Run(
        "<div id=box><div id=tall></div></div>",
        "body, div { margin: 0 } #box { height: 30px; overflow: hidden } "
        "#tall { height: 200px; background: red }");
    gfx::DisplayList list;
    layout::BuildDisplayList(*result.root, list);
    int pushes = 0;
    int pops = 0;
    for (const gfx::DisplayCommand& command : list.Commands()) {
      pushes += std::holds_alternative<gfx::PushClipCommand>(command) ? 1 : 0;
      pops += std::holds_alternative<gfx::PopClipCommand>(command) ? 1 : 0;
    }
    ExpectEqInt(pushes, 1, "one clip, for the one box that asked for it");
    ExpectEqInt(pops, 1, "and it is closed");

    // `visible` is the only value that does not clip, including the scrolling
    // ones -- a scroller clips what is outside it and offers the rest back.
    const Flexed open = Run(
        "<div id=box><div id=tall></div></div>",
        "body, div { margin: 0 } #box { height: 30px } #tall { height: 200px }");
    gfx::DisplayList unclipped;
    layout::BuildDisplayList(*open.root, unclipped);
    int unclipped_pushes = 0;
    for (const gfx::DisplayCommand& command : unclipped.Commands()) {
      unclipped_pushes += std::holds_alternative<gfx::PushClipCommand>(command) ? 1 : 0;
    }
    ExpectEqInt(unclipped_pushes, 0, "and visible content is not clipped");
  });

  // From old.reddit.com, which is ADR 0007's second compatibility target. Its
  // stylesheet says `.thing .title { overflow: hidden }` and the title is an
  // `<a>`, so the rule lands on a non-replaced inline box. CSS says `overflow`
  // does not apply there at all. We applied it, clipped to the inline's own
  // border-box geometry -- which an inline box does not have, because an inline
  // box's content lives in the line boxes of its container -- and the clip came
  // out empty. Every story title on the front page vanished, and every one of
  // them was in the display list at the right place in the right colour.
  //
  // The failure mode is the reason this is a paint-side test and not a
  // screenshot: a text command that is recorded and then clipped away is
  // indistinguishable from one that was never recorded, unless you look here.
  AddTest(tests, "Position/OverflowDoesNotApplyToAnInlineBox", [] {
    const Flexed result = Run("<body><span id=t>title</span></body>",
                              "body { margin: 0 } #t { overflow: hidden }");
    gfx::DisplayList list;
    layout::BuildDisplayList(*result.root, list);
    int pushes = 0;
    bool saw_text = false;
    for (const gfx::DisplayCommand& command : list.Commands()) {
      pushes += std::holds_alternative<gfx::PushClipCommand>(command) ? 1 : 0;
      if (const auto* text = std::get_if<gfx::DrawTextCommand>(&command)) {
        const gfx::DisplayList::TextRun* run = list.TextAt(text->text);
        saw_text = saw_text || (run != nullptr && run->text == "title");
      }
    }
    ExpectEqInt(pushes, 0, "an inline box does not clip: overflow does not apply to it");
    Expect(saw_text, "and its text survives to the display list");
  });

  // The other half of the same reddit line. `.domain a` *is* an inline-block,
  // so overflow genuinely applies -- and it must clip to the box's own padding
  // box rather than to nothing. This is the case that keeps the fix above from
  // being "inline-ish boxes never clip", which would be the easy over-correction
  // and would silently drop `text-overflow: ellipsis` containers everywhere.
  AddTest(tests, "Position/OverflowAppliesToAnInlineBlock", [] {
    const Flexed result = Run("<body><span id=d>i.redd.it</span></body>",
                              "body { margin: 0 } "
                              "#d { display: inline-block; overflow: hidden; width: 60px }");
    gfx::DisplayList list;
    layout::BuildDisplayList(*result.root, list);
    int pushes = 0;
    gfx::IntRect clip;
    bool saw_text = false;
    for (const gfx::DisplayCommand& command : list.Commands()) {
      if (const auto* push = std::get_if<gfx::PushClipCommand>(&command)) {
        ++pushes;
        clip = push->rect;
      }
      if (const auto* text = std::get_if<gfx::DrawTextCommand>(&command)) {
        const gfx::DisplayList::TextRun* run = list.TextAt(text->text);
        saw_text = saw_text || (run != nullptr && run->text == "i.redd.it");
      }
    }
    ExpectEqInt(pushes, 1, "an inline-block clips, because overflow applies to it");
    Expect(saw_text, "its text is recorded");
    ExpectEqInt(clip.width, 60, "and the clip is the box's own padding box, not an empty rect");
    Expect(clip.height > 0, "with a real height rather than zero");
  });

  // `display: inline-block` was accepted by the cascade and then laid out as
  // plain `inline`, which meant it had no geometry of its own: no width, no
  // height, no padding, and a background that painted a 0x0 rectangle. These
  // are the four things that distinguish it from an inline box, so they are the
  // four things asserted.
  AddTest(tests, "InlineBlock/HasABoxOfItsOwn", [] {
    const Flexed result =
        Run("<body><span id=a>ab</span><span id=b>cd</span></body>",
            "body { margin: 0 } span { display: inline-block; width: 40px; height: 25px }");
    const std::vector<const Box*> spans = Items(*result.root, "span");
    ExpectEqInt(static_cast<long long>(spans.size()), 2, "two boxes");
    ExpectEqInt(static_cast<long long>(spans[0]->Geometry().content.width), 40,
                "a declared width is used rather than ignored");
    ExpectEqInt(static_cast<long long>(spans[0]->Geometry().content.height), 25,
                "and so is a declared height");
    // Side by side on one line: that is the half of inline-block that is
    // *inline*. Two blocks would stack.
    ExpectEqInt(static_cast<long long>(spans[1]->Geometry().content.x), 40,
                "the second sits beside the first, not under it");
    ExpectEqInt(static_cast<long long>(spans[1]->Geometry().content.y),
                static_cast<long long>(spans[0]->Geometry().content.y),
                "on the same line");
  });

  // The other half: block on the inside. A shrink-to-fit width comes from the
  // content, not from the containing block -- an inline-block that filled its
  // container would push everything after it onto the next line, which is the
  // one thing an inline-block exists not to do.
  AddTest(tests, "InlineBlock/ShrinksToFitItsContent", [] {
    // Ten pixels per character: kAdvance is 0.5 em and the font is 20px, which
    // is the convention every measurement in this file is stated in.
    const Flexed result = Run("<body><span id=s>abcd</span>xy</body>",
                              "body { margin: 0; font-size: 20px } #s { display: inline-block }");
    const std::vector<const Box*> spans = Items(*result.root, "span");
    ExpectEqInt(static_cast<long long>(spans.size()), 1, "one box");
    ExpectEqInt(static_cast<long long>(spans[0]->Geometry().content.width + 0.5f), 40,
                "as wide as its four characters, not as wide as the 400px body");
  });

  // Its contents move with it. Geometry here is absolute, so the second pass
  // has to re-lay-out the subtree rather than translate the box -- exactly what
  // PlaceFloat does and for exactly the same reason. Getting this wrong leaves
  // the box in the right place and its text at the coordinates the *measuring*
  // pass produced, which is a page whose words are all in the top-left corner.
  AddTest(tests, "InlineBlock/ItsContentsMoveWithIt", [] {
    const Flexed result = Run("<body>xxxx<span id=s>ab</span></body>",
                              "body { margin: 0 } #s { display: inline-block }");
    const std::vector<const Box*> spans = Items(*result.root, "span");
    ExpectEqInt(static_cast<long long>(spans.size()), 1, "one box");
    const float box_left = spans[0]->Geometry().content.x;
    Expect(box_left > 0.0f, "the box was pushed right by the text before it");
    const std::vector<const Box*> texts = TextBoxesIn(*spans[0]);
    Expect(!texts.empty(), "its text survived the second pass");
    Expect(!texts[0]->Fragments().empty(), "and has a fragment");
    ExpectEqInt(static_cast<long long>(texts[0]->Fragments()[0].rect.x),
                static_cast<long long>(box_left),
                "which sits where the box ended up, not where it was measured");
  });

  // An inline-block establishes a block formatting context, so a float inside
  // it is its own business: it must not shorten the lines of the paragraph the
  // inline-block is sitting on.
  AddTest(tests, "InlineBlock/EstablishesItsOwnFormattingContext", [] {
    const Flexed with = Run(
        "<body><span id=s><i id=f>ab</i>cd</span>tail</body>",
        "body { margin: 0 } #s { display: inline-block; width: 60px } #f { float: left }");
    const std::vector<const Box*> spans = Items(*with.root, "span");
    ExpectEqInt(static_cast<long long>(spans.size()), 1, "one inline-block");
    ExpectEqInt(static_cast<long long>(spans[0]->Geometry().content.width), 60,
                "the float inside does not change the inline-block's own width");
    ExpectEqInt(static_cast<long long>(spans[0]->Geometry().content.x), 0,
                "and the inline-block still starts at the left edge of its line");
  });

  AddTest(tests, "Flex/MarginLeftAutoPushesAnItemToTheEnd", [] {
    // youtube.com's masthead puts `margin-left: auto` on the end button cluster.
    // Without absorbing free space into that margin, the search box's
    // max-content width pushes the buttons past the viewport.
    const Flexed result = Run(
        "<div class=flex><i id=a></i><b id=b></b></div>",
        std::string(kReset) +
            "i { width: 40px; height: 20px } b { width: 40px; height: 20px; margin-left: auto } "
            ".flex { width: 400px }");
    const std::vector<const Box*> first = Items(*result.root, "i");
    const std::vector<const Box*> second = Items(*result.root, "b");
    ExpectEqInt(static_cast<long long>(first.size()), 1, "leading item");
    ExpectEqInt(static_cast<long long>(second.size()), 1, "trailing item");
    ExpectEqInt(static_cast<long long>(first[0]->Geometry().content.x + 0.5f), 0,
                "first stays at start");
    ExpectEqInt(static_cast<long long>(second[0]->Geometry().content.x + 0.5f), 360,
                "auto margin eats the free space");
  });

  AddTest(tests, "Flex/AbsolutelyPositionedChildrenAreNotFlexItems", [] {
    // Masthead shell: absolute search beside inline menu and `flex:1` end
    // icons. Two failure modes pack the chip past the row: (1) treating the
    // absolute child as a flex item, (2) wrapping the inline menu into an
    // anonymous block that inherits the row's width and leaves the grower at 0.
    const Flexed result = Run(
        "<div class=row><i id=menu></i><s id=search></s><b id=end><u id=chip></u></b></div>",
        "body, div, i, s, b, u { margin: 0 } "
        ".row { display: flex; width: 400px; height: 40px } "
        "#menu { width: 40px; height: 40px } "
        "#search { position: absolute; left: 50px; width: 200px; height: 30px } "
        "#end { flex: 1; display: flex; justify-content: flex-end; height: 40px } "
        "#chip { width: 32px; height: 32px }");
    const std::vector<const Box*> ends = Items(*result.root, "b");
    const std::vector<const Box*> chips = Items(*result.root, "u");
    ExpectEqInt(static_cast<long long>(ends.size()), 1, "end cluster");
    ExpectEqInt(static_cast<long long>(chips.size()), 1, "chip");
    ExpectEqInt(static_cast<long long>(ends[0]->Geometry().content.width + 0.5f), 360,
                "flex:1 takes the space the absolute sibling does not");
    Expect(chips[0]->Geometry().content.x + chips[0]->Geometry().content.width <= 400.5f,
           "chip stays inside the row");
    ExpectEqInt(static_cast<long long>(chips[0]->Geometry().content.x + 0.5f), 368,
                "flex-end packs the chip to the row's right edge");
  });

  AddTest(tests, "Flex/AContainerIsAsTallAsItsLines", [] {
    const Flexed result = Run(
        "<div class=flex><p>a</p><p>b</p><p>c</p></div>",
        std::string(kReset) + "p { width: 120px; height: 30px } .flex { flex-wrap: wrap }");
    const std::vector<const Box*> containers = Items(*result.root, "div");
    Expect(containers.size() == 1, "one container");
    ExpectEqInt(static_cast<long long>(containers[0]->Geometry().content.height + 0.5f), 60,
                "two lines of thirty");
  });

  AddTest(tests, "Flex/ColumnMaxHeightLetsItemsShrink", [] {
    // youtube consent shape: column flex, `height: auto`, a binding `max-height`,
    // and a tall `overflow: auto; min-height: 0` body. Without a second pass that
    // treats the max as a definite main size, the body stays at its intrinsic
    // height and the footer is laid out below the dialog.
    const Flexed result = Run(
        "<div class=flex><section>"
        "<p>aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa</p>"
        "<p>bbbb bbbb bbbb bbbb bbbb bbbb bbbb bbbb</p>"
        "<p>cccc cccc cccc cccc cccc cccc cccc cccc</p>"
        "<p>dddd dddd dddd dddd dddd dddd dddd dddd</p>"
        "<p>eeee eeee eeee eeee eeee eeee eeee eeee</p>"
        "</section><footer>ok</footer></div>",
        "body, div, section, footer, p { margin: 0; padding: 0 } "
        ".flex { display: flex; flex-direction: column; width: 100px; max-height: 100px; "
        "box-sizing: border-box } "
        "section { overflow: auto; min-height: 0 } "
        "footer { height: 20px; flex-shrink: 0 }");
    const std::vector<const Box*> containers = Items(*result.root, "div");
    const std::vector<const Box*> bodies = Items(*result.root, "section");
    const std::vector<const Box*> feet = Items(*result.root, "footer");
    ExpectEqInt(static_cast<long long>(containers.size()), 1, "one container");
    ExpectEqInt(static_cast<long long>(bodies.size()), 1, "one body");
    ExpectEqInt(static_cast<long long>(feet.size()), 1, "one footer");
    ExpectEqInt(static_cast<long long>(containers[0]->Geometry().content.height + 0.5f), 100,
                "max-height is the used height");
    ExpectEqInt(static_cast<long long>(bodies[0]->Geometry().content.height + 0.5f), 80,
                "body shrinks into the free space above the footer");
    ExpectEqInt(static_cast<long long>(feet[0]->Geometry().content.y + 0.5f), 80,
                "footer stays inside the max-height box");
  });

  AddTest(tests, "Flex/NestedColumnInsideRowKeepsContentCrossSize", [] {
    // youtube home feed nudge: `#dismissible` (row) > `#content-wrapper`
    // (column) > `#text-container` (column) > title/subtitle. The text lays out
    // ~127px tall but ancestors stayed 0 with `overflow:hidden`, so the nudge
    // was invisible inside a 72px page-manager (TD-0028).
    const Flexed result = Run(
        "<div id=dismissible>"
        "<div id=wrapper><div id=header></div>"
        "<div id=text><h2>Try searching to get started</h2>"
        "<p>Start watching videos to help us build a feed.</p></div></div></div>",
        "body, div, h2, p { margin: 0; padding: 0 } "
        "#dismissible { display: flex; width: 700px; overflow: hidden; min-height: 0 } "
        "#wrapper { display: flex; flex-direction: column; width: 700px } "
        "#header { display: flex } "
        "#text { display: flex; flex-direction: column } "
        "h2 { display: block; height: 50px } "
        "p { display: block; height: 60px }");
    const Box* dismissible = nullptr;
    const Box* wrapper = nullptr;
    const Box* text = nullptr;
    result.root->ForEachDescendant([&](const Box& box) {
      if (box.Origin() == nullptr || !box.Origin()->IsElement()) {
        return;
      }
      const auto* id = static_cast<const dom::Element*>(box.Origin())->GetAttribute("id");
      if (id == nullptr) {
        return;
      }
      if (*id == "dismissible") {
        dismissible = &box;
      } else if (*id == "wrapper") {
        wrapper = &box;
      } else if (*id == "text") {
        text = &box;
      }
    });
    Expect(dismissible != nullptr && wrapper != nullptr && text != nullptr, "boxes exist");
    ExpectEqInt(static_cast<long long>(text->Geometry().content.height + 0.5f), 110,
                "text column is title+subtitle tall");
    ExpectEqInt(static_cast<long long>(wrapper->Geometry().content.height + 0.5f), 110,
                "wrapper column grows with the text item");
    ExpectEqInt(static_cast<long long>(dismissible->Geometry().content.height + 0.5f), 110,
                "row dismissible cross-size is the wrapper height");
  });

  AddTest(tests, "Flex/RowStatedHeightStretchesItems", [] {
    // TD-0028: a row flex with `height: 200px` must stretch items to that cross
    // size. Overwriting the container height after LayoutFlexChildren left
    // children at content size (youtube ytd-browse).
    const Flexed result = Run(
        "<div class=flex><section>x</section></div>",
        "body, div, section { margin: 0; padding: 0 } "
        ".flex { display: flex; width: 400px; height: 200px } "
        "section { flex: 1; min-height: 0; background: red }");
    const std::vector<const Box*> containers = Items(*result.root, "div");
    const std::vector<const Box*> sections = Items(*result.root, "section");
    ExpectEqInt(static_cast<long long>(containers.size()), 1, "one row");
    ExpectEqInt(static_cast<long long>(sections.size()), 1, "one item");
    ExpectEqInt(static_cast<long long>(containers[0]->Geometry().content.height + 0.5f), 200,
                "row uses its stated height");
    ExpectEqInt(static_cast<long long>(sections[0]->Geometry().content.height + 0.5f), 200,
                "stretch fills the definite cross size");
  });

  AddTest(tests, "Flex/RowItemPercentHeightResolvesAgainstContainer", [] {
    // height:100% is not `auto`, so stretch does not apply — the percentage
    // must resolve against the row's definite cross size instead.
    const Flexed result = Run(
        "<div class=flex><section>x</section></div>",
        "body, div, section { margin: 0; padding: 0 } "
        ".flex { display: flex; width: 400px; height: 200px } "
        "section { width: 100px; height: 100% }");
    const std::vector<const Box*> sections = Items(*result.root, "section");
    ExpectEqInt(static_cast<long long>(sections.size()), 1, "one item");
    ExpectEqInt(static_cast<long long>(sections[0]->Geometry().content.height + 0.5f), 200,
                "height:100% fills the row");
  });

  AddTest(tests, "Flex/PercentFlexBasisAgainstIndefiniteMainUsesContent", [] {
    // `flex: 1` → `flex-basis: 0%`. Against an auto-height column that
    // percentage is indefinite and must act as `auto`, so the item sizes to
    // its content instead of collapsing to 0 (youtube feed nudge / TD-0028).
    const Flexed result = Run(
        "<div class=col><div class=item><p>hello hello hello hello</p>"
        "<p>more more more more</p></div></div>",
        "body, div, p { margin: 0; padding: 0 } "
        ".col { display: flex; flex-direction: column; width: 100px } "
        ".item { display: flex; flex-direction: column; flex: 1; min-height: 0; "
        "overflow: hidden } "
        "p { height: 40px }");
    const std::vector<const Box*> items = Items(*result.root, "div");
    Expect(items.size() >= 2, "column and item");
    const Box* item = nullptr;
    for (const Box* box : items) {
      if (box->Origin() != nullptr && box->Origin()->IsElement()) {
        const auto* cls =
            static_cast<const dom::Element*>(box->Origin())->GetAttribute("class");
        if (cls != nullptr && *cls == "item") {
          item = box;
        }
      }
    }
    Expect(item != nullptr, "item box");
    ExpectEqInt(static_cast<long long>(item->Geometry().content.height + 0.5f), 80,
                "0% basis against indefinite main sizes to content, not zero");
  });
}

}  // namespace microbrowser::tests
