#include <memory>
#include <string>
#include <string_view>
#include <vector>

#include "TestSupport.h"
#include "css/StyleResolver.h"
#include "css/StyleSheet.h"
#include "html/TreeBuilder.h"
#include "layout/LayoutEngine.h"

// Flex layout.
//
// Every expectation here is a number, because that is the only way to tell a
// working flex container from one that merely stacked its children and
// happened to look right in a screenshot. Ten pixels per character at a 20px
// font, so a width is something a test can state.

namespace microbrowser::tests {

using layout::Box;
using layout::FixedTextMeasurer;
using layout::LayoutEngine;

namespace {

constexpr float kAdvance = 0.5f;

struct Flexed {
  std::unique_ptr<dom::Document> document;
  std::unique_ptr<css::StyleResolver> resolver;
  std::unique_ptr<FixedTextMeasurer> measurer;
  std::unique_ptr<Box> root;
  float height = 0.0f;
};

Flexed Run(std::string_view html, std::string_view css_text, float width = 400.0f) {
  Flexed result;
  result.document = html::ParseDocument(html);
  result.resolver = std::make_unique<css::StyleResolver>();
  result.resolver->AddStyleSheet(css::ParseStyleSheet(css_text), css::Origin::Author);
  result.measurer = std::make_unique<FixedTextMeasurer>(kAdvance);
  const LayoutEngine engine(*result.resolver, *result.measurer);
  result.root = engine.BuildBoxTree(*result.document);
  result.height = engine.Layout(*result.root, width);
  return result;
}

// Every box generated by an element with this tag, in tree order.
std::vector<const Box*> Items(const Box& root, std::string_view tag) {
  std::vector<const Box*> boxes;
  root.ForEachDescendant([&](const Box& box) {
    if (box.Origin() != nullptr && box.Origin()->TagName() == tag) {
      boxes.push_back(&box);
    }
  });
  return boxes;
}

// The items' content rectangles as "x,w" pairs, which is what nearly every
// expectation below is about. Rounded, because a distributed remainder is not
// a number a test should be pinned to the last bit of.
std::string Horizontal(const Box& root, std::string_view tag) {
  std::string out;
  for (const Box* box : Items(root, tag)) {
    if (!out.empty()) {
      out += " ";
    }
    out += std::to_string(static_cast<int>(box->Geometry().content.x + 0.5f)) + "," +
           std::to_string(static_cast<int>(box->Geometry().content.width + 0.5f));
  }
  return out;
}

std::string Vertical(const Box& root, std::string_view tag) {
  std::string out;
  for (const Box* box : Items(root, tag)) {
    if (!out.empty()) {
      out += " ";
    }
    out += std::to_string(static_cast<int>(box->Geometry().content.y + 0.5f)) + "," +
           std::to_string(static_cast<int>(box->Geometry().content.height + 0.5f));
  }
  return out;
}

// A container 300 wide with no margins anywhere, so the numbers in a test are
// the numbers flex layout produced and not a body margin.
constexpr const char* kReset =
    "body, div, span, p { margin: 0; padding: 0; border: 0; font-size: 20px } "
    ".flex { display: flex; width: 300px } ";

}  // namespace

void RegisterFlexLayoutTests(std::vector<TestCase>& tests) {
  AddTest(tests, "Flex/ItemsSitSideBySideRatherThanStacking", [] {
    // The whole point, and the thing a block container cannot do.
    const Flexed result = Run(
        "<div class=flex><p>ab</p><p>cd</p></div>",
        std::string(kReset) + "p { width: 50px }");
    ExpectEqString(Horizontal(*result.root, "p"), "0,50 50,50", "laid out along the row");
    // A 20px font makes a 24px line box, which is the height an item with one
    // line of text has.
    ExpectEqString(Vertical(*result.root, "p"), "0,24 0,24", "and at the same height");
  });

  AddTest(tests, "Flex/GrowSharesWhatIsLeftInProportion", [] {
    const Flexed result = Run(
        "<div class=flex><p id=a>a</p><p id=b>b</p></div>",
        std::string(kReset) + "p { flex-basis: 0 } #a { flex-grow: 1 } #b { flex-grow: 3 }");
    // 300 shared one-to-three.
    ExpectEqString(Horizontal(*result.root, "p"), "0,75 75,225", "in proportion to the factors");
  });

  AddTest(tests, "Flex/ShrinkIsWeightedByBaseSizeAndNotOnlyByFactor", [] {
    // The rule that keeps a long item from collapsing beside a short one: a
    // large item gives up more than a small one with the same factor. Bases of
    // 300 and 100 overflow by 100, so the first gives up 75 and the second 25.
    const Flexed result = Run(
        "<div class=flex><p id=a>a</p><p id=b>b</p></div>",
        std::string(kReset) + "#a { flex-basis: 300px } #b { flex-basis: 100px }");
    ExpectEqString(Horizontal(*result.root, "p"), "0,225 225,75", "shrunk in proportion");
  });

  AddTest(tests, "Flex/FlexOneMeansGrowShrinkAndAZeroBasis", [] {
    // `flex: 1` fills and `flex-grow: 1` does not, because the shorthand sets
    // the basis to zero and the longhand leaves it auto. Pages depend on the
    // difference and it is the most common flex mistake.
    const Flexed filled = Run("<div class=flex><p>aaaa</p><p>b</p></div>",
                              std::string(kReset) + "p { flex: 1 }");
    ExpectEqString(Horizontal(*filled.root, "p"), "0,150 150,150", "equal, whatever the content");

    const Flexed absorbed = Run("<div class=flex><p>aaaa</p><p>b</p></div>",
                                std::string(kReset) + "p { flex-grow: 1 }");
    // Content is 40 and 10 wide; the 250 left over is split evenly on top.
    ExpectEqString(Horizontal(*absorbed.root, "p"), "0,165 165,135",
                   "content size plus an equal share");
  });

  AddTest(tests, "Flex/JustifyContentPlacesTheLeftoverSpace", [] {
    const std::string markup = "<div class=flex><p>a</p><p>b</p></div>";
    const std::string base = std::string(kReset) + "p { width: 100px } .flex { ";
    // 300 wide, 200 used, 100 left over.
    ExpectEqString(Horizontal(*Run(markup, base + "justify-content: flex-start }").root, "p"),
                   "0,100 100,100", "start");
    ExpectEqString(Horizontal(*Run(markup, base + "justify-content: flex-end }").root, "p"),
                   "100,100 200,100", "end");
    ExpectEqString(Horizontal(*Run(markup, base + "justify-content: center }").root, "p"),
                   "50,100 150,100", "center");
    ExpectEqString(Horizontal(*Run(markup, base + "justify-content: space-between }").root, "p"),
                   "0,100 200,100", "space-between puts it all in the middle");
    // Half a gap at each end, so the outer spaces are half the inner one.
    ExpectEqString(Horizontal(*Run(markup, base + "justify-content: space-around }").root, "p"),
                   "25,100 175,100", "space-around");
    ExpectEqString(Horizontal(*Run(markup, base + "justify-content: space-evenly }").root, "p"),
                   "33,100 167,100", "space-evenly");
  });

  AddTest(tests, "Flex/AlignItemsPositionsAcrossTheLine", [] {
    const std::string markup =
        "<div class=flex><p id=tall>a</p><p id=short>b</p></div>";
    const std::string base =
        std::string(kReset) + "p { width: 100px } #tall { height: 100px } .flex { ";
    // The line is 100 tall because of the first item; the second is 20.
    ExpectEqString(Vertical(*Run(markup, base + "align-items: flex-start }").root, "p"),
                   "0,100 0,24", "start");
    ExpectEqString(Vertical(*Run(markup, base + "align-items: flex-end }").root, "p"),
                   "0,100 76,24", "end");
    ExpectEqString(Vertical(*Run(markup, base + "align-items: center }").root, "p"),
                   "0,100 38,24", "center");
    // Stretch is the default, and it is what makes a row of boxes with
    // different amounts of text end up the same height.
    ExpectEqString(Vertical(*Run(markup, base + "align-items: stretch }").root, "p"),
                   "0,100 0,100", "stretch");
  });

  AddTest(tests, "Flex/AlignSelfOverridesTheContainer", [] {
    const Flexed result = Run(
        "<div class=flex><p id=tall>a</p><p id=odd>b</p></div>",
        std::string(kReset) +
            "p { width: 100px } #tall { height: 100px } "
            ".flex { align-items: flex-start } #odd { align-self: flex-end }");
    ExpectEqString(Vertical(*result.root, "p"), "0,100 76,24", "one item, its own alignment");
  });

  AddTest(tests, "Flex/AColumnStacksAlongTheOtherAxis", [] {
    const Flexed result = Run(
        "<div class=flex><p>a</p><p>b</p></div>",
        std::string(kReset) + ".flex { flex-direction: column }");
    ExpectEqString(Vertical(*result.root, "p"), "0,24 24,24", "stacked down the main axis");
    // A column item stretches across the container, which is the cross axis
    // here -- the same rule as a row item stretching in height.
    ExpectEqString(Horizontal(*result.root, "p"), "0,300 0,300", "and fills it across");
  });

  AddTest(tests, "Flex/ReverseChangesWhereItemsGoAndNotWhatTheyAre", [] {
    const Flexed result = Run(
        "<div class=flex><p>a</p><p>b</p></div>",
        std::string(kReset) + "p { width: 100px } .flex { flex-direction: row-reverse }");
    // Reversing moves the main-start edge to the right, so the first item is
    // the rightmost and the 100 left over ends up on the *left*. Placing the
    // items backwards from the left edge instead would reverse their order and
    // put the free space on the wrong side -- which looks right until there is
    // any, and is the bug this test was written after finding.
    ExpectEqString(Horizontal(*result.root, "p"), "200,100 100,100",
                   "the first item sits at the right, and the gap is on the left");
  });

  AddTest(tests, "Flex/OrderReordersWithoutReparenting", [] {
    const Flexed result = Run(
        "<div class=flex><p id=a>a</p><p id=b>b</p></div>",
        std::string(kReset) + "p { width: 100px } #a { order: 2 } #b { order: 1 }");
    // `a` is still the first child and still the first box; it is drawn second.
    ExpectEqString(Horizontal(*result.root, "p"), "100,100 0,100", "b takes the first position");
  });

  AddTest(tests, "Flex/WrappingStartsANewLineWhenAnItemDoesNotFit", [] {
    const Flexed result = Run(
        "<div class=flex><p>a</p><p>b</p><p>c</p></div>",
        std::string(kReset) + "p { width: 120px; height: 30px } .flex { flex-wrap: wrap }");
    // Two fit on the first line, the third goes below it.
    ExpectEqString(Horizontal(*result.root, "p"), "0,120 120,120 0,120", "two, then one");
    ExpectEqString(Vertical(*result.root, "p"), "0,30 0,30 30,30", "the third on a second line");
  });

  AddTest(tests, "Flex/NoWrapOverflowsRatherThanBreaking", [] {
    // The default. Without shrink there is nowhere for the third to go, and it
    // overflows rather than starting a line -- which is what `nowrap` means.
    const Flexed result = Run(
        "<div class=flex><p>a</p><p>b</p><p>c</p></div>",
        std::string(kReset) + "p { width: 120px; flex-shrink: 0 }");
    ExpectEqString(Horizontal(*result.root, "p"), "0,120 120,120 240,120", "all on one line");
  });

  AddTest(tests, "Flex/GapsSitBetweenItemsAndNotAroundThem", [] {
    const Flexed result = Run(
        "<div class=flex><p>a</p><p>b</p></div>",
        std::string(kReset) + "p { flex: 1 } .flex { gap: 20px }");
    // 300 less one 20px gap, shared.
    ExpectEqString(Horizontal(*result.root, "p"), "0,140 160,140", "one gap, between the two");
  });

  AddTest(tests, "Flex/TextDirectlyInsideAContainerBecomesAnItem", [] {
    // A flex container has no lines of its own: a run of inline content is
    // wrapped in a box and becomes an item like any other. Without that, the
    // text would be laid out as if the container were a block.
    const Flexed result = Run(
        "<div class=flex>loose<p>a</p></div>",
        std::string(kReset) + "p { width: 100px }");
    const std::vector<const Box*> paragraphs = Items(*result.root, "p");
    Expect(paragraphs.size() == 1, "the paragraph is one item");
    Expect(paragraphs[0]->Geometry().content.x > 0.0f,
           "and it sits after the anonymous item holding the text");
  });

  AddTest(tests, "Flex/AContainerIsAsTallAsItsLines", [] {
    const Flexed result = Run(
        "<div class=flex><p>a</p><p>b</p><p>c</p></div>",
        std::string(kReset) + "p { width: 120px; height: 30px } .flex { flex-wrap: wrap }");
    const std::vector<const Box*> containers = Items(*result.root, "div");
    Expect(containers.size() == 1, "one container");
    ExpectEqInt(static_cast<long long>(containers[0]->Geometry().content.height + 0.5f), 60,
                "two lines of thirty");
  });
}

}  // namespace microbrowser::tests
