#pragma once

#include <cstdint>

namespace microbrowser::text {

// Character properties from the Unicode Character Database, as generated tables.
//
// ADR 0025 §1. **The tables are generated by `tools/unicode/generate.py` and checked in**, never
// hand-copied: LineBreak.txt is 3,608 lines, a transcription error in it is a class of text that
// wraps wrongly with no way to notice, and a regenerated table is diffable against the one before it.
// A build that downloaded the UCD would be a build that fails when the network does and whose output
// depends on when it ran.
//
// The classes are UAX #14's, and this browser keeps 33 of the ~40 it defines -- the ones that appear
// in the pair table `src/text/LineBreak.cpp` implements. Everything else is folded into `AL`, an
// ordinary letter, which is the specification's own fallback for an unassigned code point and is
// therefore wrong in the same direction the specification is: it breaks where a letter would break.
enum class LineBreakClass : std::uint8_t {
  BK, CR, LF, NL,                        // mandatory breaks
  SP, ZW, WJ, GL, CM,                    // spaces and joiners
  BA, HY, B2,                            // break-after, hyphen, break-either-side
  OP, CL, CP, QU,                        // brackets and quotes
  EX, IS, SY, NS, IN, NU,                // punctuation, the solidus, and numbers
  ID, CJ, H2, H3, JL, JV, JT,            // CJK ideographs and Hangul syllables
  PR, PO,                                // prefix and postfix currency
  AI, AL, SA,                            // ambiguous, ordinary letter, complex context
  EB, EM,                                // emoji base and modifier
};

// East Asian Width, and only the three values a text engine has to know. A wide character's advance
// is a property of the *character* rather than of the font -- a CJK ideograph is two columns in a
// monospaced context and, more importantly for this browser, it is the reason a run of CJK text
// measures to twice what its code point count suggests.
enum class EastAsianWidth : std::uint8_t { Neutral, Wide, Fullwidth, Halfwidth };

LineBreakClass LineBreakClassOf(std::uint32_t code_point);
EastAsianWidth WidthOf(std::uint32_t code_point);

// Whether this code point is one whose advance is two columns. `Wide` and `Fullwidth` are, `Halfwidth`
// and everything else are not -- which is the distinction the names make and the reason both are in
// the table rather than one boolean.
bool IsDoubleWidth(std::uint32_t code_point);

// Whether this code point is punctuation that CSS 2.1 s5.12.2 folds into `::first-letter`: the
// General_Category values Ps, Pe, Pi, Pf and Po -- brackets, quotes and the rest -- when they
// precede or follow the first letter.
//
// A character-property question, so it is answered here rather than in `src/layout`, which is what
// keeps the *set* out of the box tree: the dashes (Pd) are pointedly not in it, so `"T` has a first
// letter of `"T` and `--T` has one of `T`, and a layout pass guessing at that from a handful of
// ASCII characters would be right for 5 of the 339 code points the suite tests.
//
// The five classes are **CSS 2.1's** list, not CSS Pseudo-Elements 4's, which widened it to the
// whole `P*` category. The difference is exactly Pd and Pc -- `-T` has a first letter of `-` under
// this rule and of `-T` under the newer one -- and CSS 2.1 is what the 339 files of
// `css/CSS2/selectors/` are written against. No test in the checkout exercises the newer rule
// (`grep -rl first-letter third_party/wpt/css/css-pseudo/` is empty), so widening it today would be
// a change with nothing to check it.
bool IsFirstLetterPunctuation(std::uint32_t code_point);

// Whether this code point is a space separator (General_Category Zs). The companion to the above:
// `::first-letter` skips leading spaces on its way to the first letter and leaves them *outside*
// the pseudo, and the four that matter -- U+00A0, U+2002, U+2003, U+2009 -- are exactly the ones
// whitespace collapsing does not touch, so an ASCII-only test never sees them.
bool IsSpaceSeparator(std::uint32_t code_point);

}  // namespace microbrowser::text
