#pragma once

#include <cstdint>

namespace microbrowser::text {

// Character properties from the Unicode Character Database, as generated tables.
//
// ADR 0025 §1. **The tables are generated by `tools/unicode/generate.py` and checked in**, never
// hand-copied: LineBreak.txt is 3,608 lines, a transcription error in it is a class of text that
// wraps wrongly with no way to notice, and a regenerated table is diffable against the one before it.
// A build that downloaded the UCD would be a build that fails when the network does and whose output
// depends on when it ran.
//
// The classes are UAX #14's, and this browser keeps 33 of the ~40 it defines -- the ones that appear
// in the pair table `src/text/LineBreak.cpp` implements. Everything else is folded into `AL`, an
// ordinary letter, which is the specification's own fallback for an unassigned code point and is
// therefore wrong in the same direction the specification is: it breaks where a letter would break.
enum class LineBreakClass : std::uint8_t {
  BK, CR, LF, NL,                        // mandatory breaks
  SP, ZW, WJ, GL, CM,                    // spaces and joiners
  BA, HY, B2,                            // break-after, hyphen, break-either-side
  OP, CL, CP, QU,                        // brackets and quotes
  EX, IS, SY, NS, IN, NU,                // punctuation, the solidus, and numbers
  ID, CJ, H2, H3, JL, JV, JT,            // CJK ideographs and Hangul syllables
  PR, PO,                                // prefix and postfix currency
  AI, AL, SA,                            // ambiguous, ordinary letter, complex context
  EB, EM,                                // emoji base and modifier
};

// East Asian Width, and only the three values a text engine has to know. A wide character's advance
// is a property of the *character* rather than of the font -- a CJK ideograph is two columns in a
// monospaced context and, more importantly for this browser, it is the reason a run of CJK text
// measures to twice what its code point count suggests.
enum class EastAsianWidth : std::uint8_t { Neutral, Wide, Fullwidth, Halfwidth };

LineBreakClass LineBreakClassOf(std::uint32_t code_point);
EastAsianWidth WidthOf(std::uint32_t code_point);

// Whether this code point is one whose advance is two columns. `Wide` and `Fullwidth` are, `Halfwidth`
// and everything else are not -- which is the distinction the names make and the reason both are in
// the table rather than one boolean.
bool IsDoubleWidth(std::uint32_t code_point);

}  // namespace microbrowser::text
