// Where a page's geometry questions are answered.
//
// ADR 0015: `src/bindings` may see `js` and `dom` and not `layout`, because it
// is the module that runs attacker-supplied code against our data structures
// and the layout tree holds raw pointers into the box tree, the fragment list
// and the display list. So the binding layer declares an interface and the
// engine -- which legitimately sees both a document and a layout -- implements
// it. Everything crossing back is a copy.
//
// The second half of that ADR is the one that decides the shape of this file:
// these are not reads of stored values. `getBoundingClientRect` is defined to
// return the position a box *would have* if layout were up to date, so a query
// after a mutation runs layout before it answers. That is what
// EnsureLayoutClean is, and `layout.forced_by_script` is what makes the cost of
// it visible instead of mysterious.

#include <cmath>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

#include "css/MediaQuery.h"
#include "dom/FlatTree.h"
#include "engine/Page.h"
#include "gfx/ColorText.h"
#include "util/PerformanceCounters.h"
#include "util/PerformanceTrace.h"
#include "util/StringUtil.h"

namespace microbrowser::engine {

namespace {

using util::AddPerformanceCounter;
using util::PerfCounterId;

bindings::GeometryRect ToRect(const gfx::FloatRect& rect, float scroll_x, float scroll_y) {
  return bindings::GeometryRect{rect.x - scroll_x, rect.y - scroll_y, rect.width, rect.height};
}

using ElementBoxMap = std::unordered_map<const dom::Element*, layout::Box*>;

// The first box generated by `element`, via the index `EnsureBoxTree` built.
//
// One element can generate several boxes -- a block with mixed children gets
// anonymous blocks, and a wrapped inline occupies one rectangle per line -- so
// "the box" is a simplification. It is the right one for the block-level case
// that every metric here is defined against, and the inline case is handled by
// UnionOfFragments below rather than by pretending the first box has the whole
// element's geometry.
//
// A tree walk per query is O(boxes): youtube's IntersectionObserver alone
// samples thousands of times against a six-figure box tree. The map is the
// honest fix session 7 deferred.
const layout::Box* BoxFor(const ElementBoxMap& map, const dom::Element& element) {
  AddPerformanceCounter(PerfCounterId::LayoutBoxLookups);
  const auto it = map.find(&element);
  if (it == map.end()) {
    return nullptr;
  }
  AddPerformanceCounter(PerfCounterId::LayoutBoxLookupHits);
  return it->second;
}

// Document scroll plus every ancestor scroll container's offset. `getBoundingClientRect`
// is in viewport coordinates; layout stores document coordinates, so each
// scrolled ancestor between the box and the viewport must be subtracted. The
// box itself is not: a scroller's own border box does not move when it scrolls
// — only its descendants do. Skipping ancestors left youtube's consent dialog
// `scrollTop` changing while Accept's rect stayed off-screen.
//
// `position:fixed` (and anything under one) is laid out against the viewport
// already — paint zeroes the scroll translation for those boxes — so document
// scroll must not be subtracted or Accept reports a large negative `top` after
// the page scrolls (TD-0036 made that reachable).
bool UnderFixedPosition(const ElementBoxMap& map, const dom::Element& element) {
  for (const dom::Node* at = &element; at != nullptr; at = at->Parent()) {
    if (!at->IsElement()) {
      continue;
    }
    const layout::Box* box = BoxFor(map, static_cast<const dom::Element&>(*at));
    if (box != nullptr && box->Style().position == css::Position::Fixed) {
      return true;
    }
  }
  return false;
}

void AncestorScrollOffsets(const ElementBoxMap& map, const dom::Element& element,
                           float document_scroll_y, float& scroll_x, float& scroll_y) {
  scroll_x = 0.0f;
  scroll_y = UnderFixedPosition(map, element) ? 0.0f : document_scroll_y;
  for (const dom::Node* at = element.Parent(); at != nullptr; at = at->Parent()) {
    if (!at->IsElement()) {
      continue;
    }
    const layout::Box* ancestor = BoxFor(map, static_cast<const dom::Element&>(*at));
    if (ancestor == nullptr || !ancestor->IsScrollContainer()) {
      continue;
    }
    scroll_x += ancestor->ScrollOffset().x;
    scroll_y += ancestor->ScrollOffset().y;
  }
}

// The same lookup, on a tree the caller may write to. Scrolling a box is the
// one geometry operation that is a command rather than a question, and it is
// the only reason a non-const box is reached from here.
layout::Box* MutableBoxFor(ElementBoxMap& map, const dom::Element& element) {
  AddPerformanceCounter(PerfCounterId::LayoutBoxLookups);
  const auto it = map.find(&element);
  if (it == map.end()) {
    return nullptr;
  }
  AddPerformanceCounter(PerfCounterId::LayoutBoxLookupHits);
  return it->second;
}

// The path from the root box to `element`'s box, root first. `scrollIntoView`
// needs the ancestors and not just the target, because every scrolling one of
// them has to move.
bool BoxChainTo(layout::Box& box, const dom::Element& element,
                std::vector<layout::Box*>& out) {
  out.push_back(&box);
  if (box.Origin() == &element) {
    return true;
  }
  for (const std::unique_ptr<layout::Box>& child : box.Children()) {
    if (BoxChainTo(*child, element, out)) {
      return true;
    }
  }
  out.pop_back();
  return false;
}

// Every rectangle a box actually occupies, unioned.
//
// An `Inline` box has no geometry of its own -- line layout walks *through* it
// to reach the text inside, and its content lives in the line boxes of its
// container. So the honest answer for `<a>` or `<span>` is the union of the
// fragments underneath it, which is also exactly what the specification says
// `getBoundingClientRect` returns: the union of the border boxes of all the
// fragments the element generates.
//
// Without this, every inline element on every page reports a zero rectangle,
// and a page that positions a tooltip against one puts it in the corner.
gfx::FloatRect UnionOfFragments(const layout::Box& box) {
  gfx::FloatRect united;
  if (box.GetKind() == layout::Box::Kind::Text) {
    for (const layout::TextFragment& fragment : box.Fragments()) {
      united = united.United(fragment.rect);
    }
  } else if (box.GetKind() != layout::Box::Kind::Inline) {
    united = united.United(box.Geometry().BorderBox());
  }
  for (const std::unique_ptr<layout::Box>& child : box.Children()) {
    united = united.United(UnionOfFragments(*child));
  }
  return united;
}

// A number as CSS writes it: no trailing zeros, and no exponent.
std::string Number(float value) {
  if (!std::isfinite(value)) {
    return "0";
  }
  // Two decimals is what every engine's resolved value carries, and rounding
  // here rather than at the reader is what stops `100.00000762939453px` from
  // reaching a page that concatenates it into a style.
  std::string text = std::to_string(std::round(value * 100.0f) / 100.0f);
  const std::size_t dot = text.find('.');
  if (dot == std::string::npos) {
    return text;
  }
  text.erase(text.find_last_not_of('0') + 1);
  if (!text.empty() && text.back() == '.') {
    text.pop_back();
  }
  return text.empty() ? "0" : text;
}

std::string Pixels(float value) { return Number(value) + "px"; }

// A colour as `getComputedStyle` reports one, from the one place that knows how a colour is written
// down. It used to be a copy here; the inline-style setter needs the same spelling, and two of them
// would be two answers to the same question.
std::string ColorText(const gfx::Color& color) { return gfx::SerializeColorText(color); }

// A computed length. `em` and `rem` are folded into pixels because that is what
// the computed value of a length *is*; a percentage is carried because it has
// no meaning without a containing block, and `auto` is a keyword rather than a
// number.
std::string LengthText(const css::Length& length, float font_size) {
  switch (length.unit) {
    case css::Length::Unit::Auto:
      return "auto";
    case css::Length::Unit::Percent:
      return Number(length.value) + "%";
    case css::Length::Unit::Pixels:
    case css::Length::Unit::Em:
    case css::Length::Unit::Rem:
      break;
  }
  return Pixels(length.Resolve(font_size, 0.0f));
}

const char* DisplayText(css::Display display) {
  switch (display) {
    case css::Display::Inline: return "inline";
    case css::Display::Block: return "block";
    case css::Display::InlineBlock: return "inline-block";
    case css::Display::ListItem: return "list-item";
    case css::Display::Grid: return "grid";
    case css::Display::InlineGrid: return "inline-grid";
    case css::Display::Table: return "table";
    case css::Display::TableCaption: return "table-caption";
    case css::Display::TableColumnGroup: return "table-column-group";
    case css::Display::TableColumn: return "table-column";
    case css::Display::TableHeaderGroup: return "table-header-group";
    case css::Display::TableFooterGroup: return "table-footer-group";
    case css::Display::TableRowGroup: return "table-row-group";
    case css::Display::TableRow: return "table-row";
    case css::Display::TableCell: return "table-cell";
    case css::Display::Flex: return "flex";
    case css::Display::InlineFlex: return "inline-flex";
    case css::Display::None: return "none";
  }
  return "inline";
}

const char* PositionText(css::Position position) {
  switch (position) {
    case css::Position::Static: return "static";
    case css::Position::Relative: return "relative";
    case css::Position::Absolute: return "absolute";
    case css::Position::Fixed: return "fixed";
    case css::Position::Sticky: return "sticky";
  }
  return "static";
}

const char* OverflowText(css::Overflow overflow) {
  switch (overflow) {
    case css::Overflow::Visible: return "visible";
    case css::Overflow::Hidden: return "hidden";
    case css::Overflow::Scroll: return "scroll";
    case css::Overflow::Auto: return "auto";
  }
  return "visible";
}

// The properties whose resolved value is the *used* value -- the ones that come
// out of layout in pixels rather than out of the cascade as authored.
//
// This is the split ADR 0015 calls the difficult half of `getComputedStyle`:
// the specification's "resolved value" is the used value for exactly this set
// and the computed value for everything else, and an implementation that
// answered `width` with the authored `auto` would be present, plausible and
// wrong. A page that lays itself out from a returned "auto" fails somewhere
// else entirely.
//
// The `inset` properties are deliberately *not* here, and that is a stated
// deviation rather than an oversight: their used value is an offset from a
// containing block that this box tree does not record, so they are answered
// from the cascade -- `auto`, or the length as written. See the session log.
enum class Used : std::uint8_t {
  None,
  ContentWidth,
  ContentHeight,
  MarginTop, MarginRight, MarginBottom, MarginLeft,
  PaddingTop, PaddingRight, PaddingBottom, PaddingLeft,
  BorderTopWidth, BorderRightWidth, BorderBottomWidth, BorderLeftWidth,
};

Used UsedKindOf(std::string_view property) {
  struct Entry {
    std::string_view name;
    Used kind;
  };
  static constexpr Entry kEntries[] = {
      {"width", Used::ContentWidth},
      {"height", Used::ContentHeight},
      {"margin-top", Used::MarginTop},
      {"margin-right", Used::MarginRight},
      {"margin-bottom", Used::MarginBottom},
      {"margin-left", Used::MarginLeft},
      {"padding-top", Used::PaddingTop},
      {"padding-right", Used::PaddingRight},
      {"padding-bottom", Used::PaddingBottom},
      {"padding-left", Used::PaddingLeft},
      {"border-top-width", Used::BorderTopWidth},
      {"border-right-width", Used::BorderRightWidth},
      {"border-bottom-width", Used::BorderBottomWidth},
      {"border-left-width", Used::BorderLeftWidth},
  };
  for (const Entry& entry : kEntries) {
    if (entry.name == property) {
      return entry.kind;
    }
  }
  return Used::None;
}

std::string UsedValueOf(const layout::Box& box, Used kind) {
  const layout::BoxGeometry& geometry = box.Geometry();
  const float font_size = box.Style().font_size;
  switch (kind) {
    case Used::None:
      break;
    case Used::ContentWidth: return Pixels(geometry.content.width);
    case Used::ContentHeight: return Pixels(geometry.content.height);
    case Used::MarginTop: return Pixels(geometry.margin.top.Resolve(font_size, 0.0f));
    case Used::MarginRight: return Pixels(geometry.margin.right.Resolve(font_size, 0.0f));
    case Used::MarginBottom: return Pixels(geometry.margin.bottom.Resolve(font_size, 0.0f));
    case Used::MarginLeft: return Pixels(geometry.margin.left.Resolve(font_size, 0.0f));
    case Used::PaddingTop: return Pixels(geometry.padding.top.Resolve(font_size, 0.0f));
    case Used::PaddingRight: return Pixels(geometry.padding.right.Resolve(font_size, 0.0f));
    case Used::PaddingBottom: return Pixels(geometry.padding.bottom.Resolve(font_size, 0.0f));
    case Used::PaddingLeft: return Pixels(geometry.padding.left.Resolve(font_size, 0.0f));
    case Used::BorderTopWidth: return Pixels(geometry.border.top.Resolve(font_size, 0.0f));
    case Used::BorderRightWidth: return Pixels(geometry.border.right.Resolve(font_size, 0.0f));
    case Used::BorderBottomWidth: return Pixels(geometry.border.bottom.Resolve(font_size, 0.0f));
    case Used::BorderLeftWidth: return Pixels(geometry.border.left.Resolve(font_size, 0.0f));
  }
  return std::string();
}

// The computed value of one property, serialized.
//
// The table is what this engine actually stores, which is what makes it
// honest: a property missing from here is one the cascade does not keep, and
// reporting the empty string for it is the specification's answer for a
// property the implementation does not support. Inventing a plausible initial
// value for `transform` would be worse -- a page that reads one back believes
// the property applies.
std::optional<std::string> ComputedValueOf(const css::ComputedStyle& style,
                                           std::string_view property) {
  const float font_size = style.font_size;
  if (property == "display") return std::string(DisplayText(style.display));
  if (property == "position") return std::string(PositionText(style.position));
  if (property == "overflow-x") return std::string(OverflowText(style.overflow_x));
  if (property == "overflow-y") return std::string(OverflowText(style.overflow_y));
  // Shorthand: when both axes agree, one token; otherwise the two-value form.
  // Absent entirely, `cs.overflow` is undefined and iron-fit / consent CSS that
  // feature-detects or copies `overflow` silently no-ops (youtube's dialog).
  if (property == "overflow") {
    if (style.overflow_x == style.overflow_y) {
      return std::string(OverflowText(style.overflow_x));
    }
    return std::string(OverflowText(style.overflow_x)) + " " + OverflowText(style.overflow_y);
  }
  if (property == "box-sizing") {
    return std::string(style.box_sizing == css::BoxSizing::BorderBox ? "border-box"
                                                                     : "content-box");
  }
  if (property == "color") return ColorText(style.color);
  if (property == "background-color") return ColorText(style.background_color);
  if (property == "font-size") return Pixels(font_size);
  if (property == "font-weight") return Number(style.font_weight);
  if (property == "font-style") {
    return std::string(style.font_style == css::FontStyle::Italic ? "italic" : "normal");
  }
  if (property == "font-family") {
    std::string out;
    for (const std::string& family : style.font_family) {
      out += out.empty() ? "" : ", ";
      out += family;
    }
    return out;
  }
  if (property == "line-height") {
    // Zero is `normal`, which is a multiple of the font size rather than a
    // length -- resolved by layout, and reported as the keyword until it is.
    return style.line_height == 0.0f ? std::string("normal") : Pixels(style.line_height);
  }
  if (property == "text-align") {
    switch (style.text_align) {
      case css::TextAlign::Start: return std::string("start");
      case css::TextAlign::End: return std::string("end");
      case css::TextAlign::Left: return std::string("left");
      case css::TextAlign::Right: return std::string("right");
      case css::TextAlign::Center: return std::string("center");
      case css::TextAlign::Justify: return std::string("justify");
    }
  }
  if (property == "white-space") {
    switch (style.white_space) {
      case css::WhiteSpace::Normal: return std::string("normal");
      case css::WhiteSpace::Pre: return std::string("pre");
      case css::WhiteSpace::NoWrap: return std::string("nowrap");
      case css::WhiteSpace::PreWrap: return std::string("pre-wrap");
    }
  }
  if (property == "float") {
    switch (style.css_float) {
      case css::Float::None: return std::string("none");
      case css::Float::Left: return std::string("left");
      case css::Float::Right: return std::string("right");
    }
  }
  if (property == "clear") {
    switch (style.clear) {
      case css::Clear::None: return std::string("none");
      case css::Clear::Left: return std::string("left");
      case css::Clear::Right: return std::string("right");
      case css::Clear::Both: return std::string("both");
    }
  }
  if (property == "visibility") {
    switch (style.visibility) {
      case css::Visibility::Visible: return std::string("visible");
      case css::Visibility::Hidden: return std::string("hidden");
    }
  }
  if (property == "opacity") {
    return Number(style.opacity);
  }
  if (property == "flex-direction") {
    switch (style.flex.direction) {
      case css::FlexDirection::Row: return std::string("row");
      case css::FlexDirection::RowReverse: return std::string("row-reverse");
      case css::FlexDirection::Column: return std::string("column");
      case css::FlexDirection::ColumnReverse: return std::string("column-reverse");
    }
  }
  if (property == "flex-wrap") {
    switch (style.flex.wrap) {
      case css::FlexWrap::NoWrap: return std::string("nowrap");
      case css::FlexWrap::Wrap: return std::string("wrap");
      case css::FlexWrap::WrapReverse: return std::string("wrap-reverse");
    }
  }
  if (property == "flex-grow") {
    return Number(style.flex.grow);
  }
  if (property == "flex-shrink") {
    return Number(style.flex.shrink);
  }
  if (property == "flex-basis") {
    return LengthText(style.flex.basis, font_size);
  }
  if (property == "align-items") {
    switch (style.flex.align_items) {
      case css::Alignment::Auto: return std::string("normal");
      case css::Alignment::Stretch: return std::string("stretch");
      case css::Alignment::FlexStart: return std::string("flex-start");
      case css::Alignment::FlexEnd: return std::string("flex-end");
      case css::Alignment::Center: return std::string("center");
      case css::Alignment::Baseline: return std::string("baseline");
    }
  }
  if (property == "align-self") {
    switch (style.flex.align_self) {
      case css::Alignment::Auto: return std::string("auto");
      case css::Alignment::Stretch: return std::string("stretch");
      case css::Alignment::FlexStart: return std::string("flex-start");
      case css::Alignment::FlexEnd: return std::string("flex-end");
      case css::Alignment::Center: return std::string("center");
      case css::Alignment::Baseline: return std::string("baseline");
    }
  }
  if (property == "justify-content") {
    switch (style.flex.justify_content) {
      case css::Distribution::FlexStart: return std::string("flex-start");
      case css::Distribution::FlexEnd: return std::string("flex-end");
      case css::Distribution::Center: return std::string("center");
      case css::Distribution::SpaceBetween: return std::string("space-between");
      case css::Distribution::SpaceAround: return std::string("space-around");
      case css::Distribution::SpaceEvenly: return std::string("space-evenly");
      case css::Distribution::Stretch: return std::string("stretch");
    }
  }
  if (property == "order") {
    return std::to_string(style.flex.order);
  }
  if (property == "pointer-events") {
    return std::string(style.pointer_events == css::PointerEvents::None ? "none" : "auto");
  }
  if (property == "z-index") {
    return style.z_index.has_value() ? std::to_string(*style.z_index) : std::string("auto");
  }
  if (property == "top") return LengthText(style.inset.top, font_size);
  if (property == "right") return LengthText(style.inset.right, font_size);
  if (property == "bottom") return LengthText(style.inset.bottom, font_size);
  if (property == "left") return LengthText(style.inset.left, font_size);
  if (property == "width") return LengthText(style.width, font_size);
  if (property == "height") return LengthText(style.height, font_size);
  if (property == "min-width") return LengthText(style.min_width, font_size);
  if (property == "min-height") return LengthText(style.min_height, font_size);
  // `max-width` / `max-height` initial value is `none`, not `auto`. The cascade
  // stores the unbounded case as Length::Auto (ClampBy reads it as no bound),
  // but iron-fit's `_discoverInfo` does `sizedBy.height = maxHeight !== "none"`
  // — answering `"auto"` makes every unconstrained box look pre-sized, so
  // `constrain()` never writes a viewport max-height and youtube's consent
  // dialog stays 1500px tall with Accept below the fold.
  if (property == "max-width") {
    return style.max_width.IsAuto() ? std::string("none")
                                    : LengthText(style.max_width, font_size);
  }
  if (property == "max-height") {
    return style.max_height.IsAuto() ? std::string("none")
                                     : LengthText(style.max_height, font_size);
  }
  if (property == "margin-top") return LengthText(style.margin.top, font_size);
  if (property == "margin-right") return LengthText(style.margin.right, font_size);
  if (property == "margin-bottom") return LengthText(style.margin.bottom, font_size);
  if (property == "margin-left") return LengthText(style.margin.left, font_size);
  if (property == "padding-top") return LengthText(style.padding.top, font_size);
  if (property == "padding-right") return LengthText(style.padding.right, font_size);
  if (property == "padding-bottom") return LengthText(style.padding.bottom, font_size);
  if (property == "padding-left") return LengthText(style.padding.left, font_size);
  if (property == "border-top-width") return LengthText(style.border_width.top, font_size);
  if (property == "border-right-width") return LengthText(style.border_width.right, font_size);
  if (property == "border-bottom-width") return LengthText(style.border_width.bottom, font_size);
  if (property == "border-left-width") return LengthText(style.border_width.left, font_size);
  if (property == "background-image") {
    return style.background.image.empty() ? std::string("none")
                                          : "url(\"" + style.background.image + "\")";
  }
  if (property == "aspect-ratio") {
    return style.aspect_ratio == 0.0f ? std::string("auto") : Number(style.aspect_ratio);
  }
  return std::nullopt;
}

}  // namespace

void Page::EnsureLayoutClean() {
  if (document_ == nullptr) {
    return;
  }
  if (boxes_ != nullptr && layout_.document_version == document_->MutationVersion() &&
      layout_.laid_out_width == layout_.width) {
    return;
  }
  // A page can reach this in a loop -- write a style, read a rect, write
  // another -- and make the browser do unbounded work synchronously. That is
  // true of every browser and it is not a vulnerability; what makes it
  // diagnosable rather than mysterious is that the count goes up once per
  // iteration and the scope attributes the time to script rather than to the
  // frame. See ADR 0015.
  util::PerformanceTrace::Scope scope("layout/forced");
  AddPerformanceCounter(PerfCounterId::LayoutForcedByScript);
  Layout(layout_.width);
}

std::optional<bindings::BoxGeometry> Page::QueryBox(const dom::Node& node) {
  if (!node.IsElement()) {
    return std::nullopt;  // only an element generates boxes
  }
  EnsureLayoutClean();
  if (boxes_ == nullptr) {
    return std::nullopt;
  }
  const auto& element = static_cast<const dom::Element&>(node);
  const layout::Box* box = BoxFor(layout_.box_by_element, element);
  if (box == nullptr) {
    // `display: none`, or a subtree script built and has not inserted. Both
    // genuinely have no geometry, and the caller reports the all-zero rectangle
    // the specification asks for.
    return std::nullopt;
  }

  float scroll_x = 0.0f;
  float scroll_y = 0.0f;
  AncestorScrollOffsets(layout_.box_by_element, element, layout_.scroll_y, scroll_x, scroll_y);
  bindings::BoxGeometry answer;
  if (box->GetKind() == layout::Box::Kind::Inline) {
    // An inline box carries no geometry of its own; its fragments do. The three
    // boxes collapse to one here because a fragment has no padding or border of
    // its own to subtract -- which is a real approximation, and a much smaller
    // one than reporting zero.
    const bindings::GeometryRect united =
        ToRect(UnionOfFragments(*box), scroll_x, scroll_y);
    return bindings::BoxGeometry{united, united, united};
  }
  answer.border_box = ToRect(box->Geometry().BorderBox(), scroll_x, scroll_y);
  answer.padding_box = ToRect(box->Geometry().PaddingBox(), scroll_x, scroll_y);
  answer.content_box = ToRect(box->Geometry().content, scroll_x, scroll_y);
  if (IsViewportScroller(element)) {
    // `document.documentElement.scrollTop` is the *document's* offset, not the
    // root element's own -- which is the one thing about the scroll API every
    // page relies on and no markup expresses. `document.body.scrollTop` reads
    // the same number in the quirks-mode half of that rule; only the standards
    // half is implemented, because that is the one a page written this decade
    // takes.
    answer.scroll_x = 0.0f;
    answer.scroll_y = scroll_y;
    answer.scroll_width = box->Geometry().PaddingBox().width;
    answer.scroll_height = std::max(content_height_, viewport_.viewport_height);
  } else {
    answer.scroll_x = box->ScrollOffset().x;
    answer.scroll_y = box->ScrollOffset().y;
    if (box->IsScrollContainer()) {
      answer.scroll_width = box->ScrollableOverflow().width;
      answer.scroll_height = box->ScrollableOverflow().height;
    } else {
      // Scrollable overflow is only measured for scroll containers. For
      // `overflow: visible` the CSSOM still exposes a scroll size — at least the
      // padding box — so `scrollWidth`/`scrollHeight` are never zero on a box
      // that has a non-zero client size (youtube's consent dialog was).
      const gfx::FloatRect padding = box->Geometry().PaddingBox();
      answer.scroll_width = padding.width;
      answer.scroll_height = padding.height;
    }
  }
  return answer;
}

double Page::QueryDevicePixelRatio() const {
  // Unquantised, and the quantising happens at the seam. See the note in bindings/Geometry.h: the same
  // number selects an `<img srcset>` candidate, and the image chosen for a display should be the one
  // that display wants even while a page is told a reduced ratio.
  return static_cast<double>(viewport_.device_pixel_ratio);
}

bindings::GeometryRect Page::QueryViewport() {
  // No EnsureLayoutClean: the viewport is what the *browser* told this page it
  // has, not something a layout computes. Forcing one here would make reading
  // `window.innerWidth` in a loop cost a relayout per iteration for an answer
  // that cannot have changed.
  return bindings::GeometryRect{0.0f, 0.0f, viewport_.viewport_width,
                                viewport_.viewport_height};
}

bool Page::QueryMediaMatches(std::string_view query) {
  // No EnsureLayoutClean, for the reason QueryViewport gives: a media query is
  // a function of what the browser told this page it has, and running a layout
  // could not change the answer.
  //
  // The same evaluator `@media`, `<source media>` and `sizes` go through, and
  // the same `viewport_` -- which is the point of routing this through the
  // geometry seam rather than giving the binding layer a context of its own.
  // Two answers to "is this viewport narrow" is how a page's stylesheet and its
  // script come to disagree about which layout it is in.
  return css::MediaQueryListMatches(query, viewport_);
}

bool Page::IsViewportScroller(const dom::Element& element) const {
  return document_ != nullptr && document_->DocumentElement() == &element;
}

void Page::SetScrollOffset(const dom::Node& node, float x, float y) {
  if (!node.IsElement()) {
    return;
  }
  EnsureLayoutClean();
  if (boxes_ == nullptr) {
    return;
  }
  const auto& element = static_cast<const dom::Element&>(node);
  if (IsViewportScroller(element)) {
    // Clamped against the document, exactly as a wheel is. `scrollTop = 1e9` is
    // how a page scrolls to the bottom, so an out-of-range value is ordinary.
    const float limit = std::max(0.0f, content_height_ - viewport_.viewport_height);
    SetScrollOffsetY(std::clamp(y, 0.0f, limit));
    return;
  }
  layout::Box* box = MutableBoxFor(layout_.box_by_element, element);
  if (box == nullptr || !box->IsScrollContainer()) {
    return;
  }
  const gfx::FloatPoint limit = layout::MaxScrollOffset(*box);
  const gfx::FloatPoint wanted{std::clamp(x, 0.0f, limit.x), std::clamp(y, 0.0f, limit.y)};
  if (wanted == box->ScrollOffset()) {
    return;
  }
  box->SetScrollOffset(wanted);
  scroll_.offsets[&element] = wanted;
  NoteScrolled(&element);
}

void Page::ScrollIntoView(const dom::Node& node) {
  if (!node.IsElement()) {
    return;
  }
  EnsureLayoutClean();
  if (boxes_ == nullptr) {
    return;
  }
  const auto& element = static_cast<const dom::Element&>(node);
  // Every scrolling ancestor, not just the nearest: an item in a menu inside a
  // scrolled page needs both moved, and an implementation that moved one is the
  // one that looks right in a demo and fails on a real page. The chain is built
  // from the root down, and walked from the target outwards.
  std::vector<layout::Box*> chain;
  if (!BoxChainTo(*boxes_, element, chain) || chain.empty()) {
    return;
  }
  const gfx::FloatRect target = chain.back()->Geometry().BorderBox();
  // Accumulated as the walk goes outward, because moving an outer scroller
  // changes where the target sits inside it.
  float shift_x = 0.0f;
  float shift_y = 0.0f;
  for (std::size_t i = chain.size() - 1; i-- > 0;) {
    layout::Box* box = chain[i];
    if (!box->IsScrollContainer()) {
      continue;
    }
    const gfx::FloatRect port = box->Geometry().PaddingBox();
    const gfx::FloatPoint limit = layout::MaxScrollOffset(*box);
    const gfx::FloatPoint was = box->ScrollOffset();
    // The block-start edge, which is what `scrollIntoView()` with no argument
    // means. Clamped into the range the box can reach, so an element already
    // visible near the bottom is not yanked to the top of a box that cannot
    // scroll that far.
    const gfx::FloatPoint wanted{
        std::clamp(target.x + shift_x - port.x, 0.0f, limit.x),
        std::clamp(target.y + shift_y - port.y, 0.0f, limit.y)};
    if (wanted != was) {
      box->SetScrollOffset(wanted);
      if (box->Origin() != nullptr) {
        scroll_.offsets[box->Origin()] = wanted;
        NoteScrolled(box->Origin());
      }
    }
    shift_x += was.x - wanted.x;
    shift_y += was.y - wanted.y;
  }
  // And the document itself, which is the outermost scroller and the one with
  // no box of its own. Skip when the target is under `position:fixed`: fixed
  // boxes do not move with the document, and scrolling it by their layout Y
  // yanks the page away from a consent dialog (youtube Accept after TD-0036
  // made the document actually scrollable).
  bool under_fixed = false;
  for (const layout::Box* box : chain) {
    if (box->Style().position == css::Position::Fixed) {
      under_fixed = true;
      break;
    }
  }
  if (!under_fixed) {
    const float limit = std::max(0.0f, content_height_ - viewport_.viewport_height);
    SetScrollOffsetY(std::clamp(target.y + shift_y, 0.0f, limit));
  }
}

std::optional<std::string> Page::QueryUsedValue(const dom::Element& element,
                                                std::string_view property) {
  // Lowercased and trimmed here rather than by the caller: a page writes
  // `getPropertyValue(' Width ')` far less often than it writes
  // `style.Width`, and both have to find the same entry.
  std::string name(util::TrimAscii(property));
  for (char& c : name) {
    c = c >= 'A' && c <= 'Z' ? static_cast<char>(c - 'A' + 'a') : c;
  }
  // Unconditionally, not only for a used value. A computed value has to reflect
  // what the document says *now* -- and since ADR 0019 the cascade itself can
  // change without a node moving, because a `<style>` inside a shadow root is
  // collected at layout and is unreachable from the document walk that finds the
  // rest. A `color` read that skipped this answered from a cascade that had never
  // seen the component's own stylesheet.
  EnsureLayoutClean();
  const Used used = UsedKindOf(name);
  if (used != Used::None) {
    if (boxes_ != nullptr) {
      if (const layout::Box* box = BoxFor(layout_.box_by_element, element)) {
        return UsedValueOf(*box, used);
      }
    }
    // No box: `display: none`, and the specification says the resolved value is
    // then the computed value. Falls through rather than answering zero, which
    // would tell a page a hidden element is 0px wide when it is `auto`.
  }

  // The computed value. Read off the box when there is one, because layout has
  // already resolved the cascade for it and a second resolution is a second
  // chance to disagree. Otherwise the cascade is walked down the ancestor
  // chain, which is what makes a `display: none` element still answerable.
  if (boxes_ != nullptr) {
    if (const layout::Box* box = BoxFor(layout_.box_by_element, element)) {
      return ComputedValueOf(box->Style(), name);
    }
  }
  return ComputedValueOf(StyleWithoutBox(element), name);
}

std::optional<bindings::ImageState> Page::QueryImageState(const dom::Element& element) {
  if (element.TagName() != "img") {
    return std::nullopt;
  }
  const auto selected = resources_.selected_image_urls.find(&element);
  if (selected == resources_.selected_image_urls.end()) {
    return std::nullopt;
  }
  const std::shared_ptr<const gfx::Image> image = ImageFor(selected->second);
  if (image == nullptr || !image->IsValid()) {
    return bindings::ImageState{};
  }
  bindings::ImageState state;
  state.natural_width = image->Width();
  state.natural_height = image->Height();
  state.complete = true;
  return state;
}

css::ComputedStyle Page::StyleWithoutBox(const dom::Element& element) const {
  // The ancestors, root first, so inheritance runs the one direction it can:
  // StyleFor takes the parent's already-computed style, and walking up per
  // property instead would resolve the cascade once per ancestor per read.
  // The *flat* ancestor chain: through the host when a shadow boundary is
  // reached, because inheritance crosses one even though matching does not
  // (ADR 0019 §3). Without this a node in a shadow tree inherits from nothing,
  // and `getComputedStyle` inside a component answers with the initial values.
  std::vector<const dom::Element*> chain;
  for (const dom::Node* at = &element; at != nullptr;) {
    if (at->IsElement()) {
      chain.push_back(static_cast<const dom::Element*>(at));
    }
    if (at->Parent() != nullptr) {
      at = at->Parent();
      continue;
    }
    at = dom::ShadowHostOf(*at);
  }
  css::ComputedStyle style = css::StyleResolver::InitialStyle();
  std::uint64_t style_id = 0;
  for (std::size_t i = chain.size(); i-- > 0;) {
    style = resolver_.StyleFor(*chain[i], style, style_id, &style_id);
  }
  return style;
}

dom::Element* Page::ElementAtViewport(float x, float y) {
  // CSSOM View §elementsFromPoint: coordinates outside the viewport yield an
  // empty list, so elementFromPoint returns null. Hitting below-fold youtube
  // thumbs through a negative or >innerHeight Y made YoutubeResultsLooksReady
  // (and page scripts) treat off-screen geometry as topmost (TD-0037).
  //
  // Per axis, and only where the viewport has a size: `viewport_` is zero until something calls
  // SetViewport, and a page laid out without one has a width and an unknown height rather than a
  // viewport nothing is inside. Culling against zero made every `elementFromPoint` on such a page
  // answer null, which is not "outside the viewport" -- it is "nobody said how big the window is".
  const bool wide = viewport_.viewport_width > 0.0f;
  const bool tall = viewport_.viewport_height > 0.0f;
  if (x < 0.0f || y < 0.0f || (wide && x >= viewport_.viewport_width) ||
      (tall && y >= viewport_.viewport_height)) {
    util::AddPerformanceCounter(util::PerfCounterId::GeometryElementFromPointOutsideViewport);
    return nullptr;
  }
  const gfx::FloatPoint document_point{x, y + layout_.scroll_y};
  const dom::Element* hit = ElementAt(document_point);
  return hit == nullptr ? nullptr : const_cast<dom::Element*>(hit);
}

}  // namespace microbrowser::engine
