#!/usr/bin/env python3
"""Generates src/text/UnicodeTables.inc from the Unicode Character Database.

ADR 0025 §1. **The tables are generated, never hand-copied**, and that is the whole point of this
file existing: LineBreak.txt has 3,608 lines and EastAsianWidth.txt has 2,621, a transcription error
in either is a class of text that wraps or measures wrongly with no way to notice, and a regenerated
table is diffable against the version before it.

It writes a *ranged* table rather than a per-code-point one. The properties are overwhelmingly
contiguous -- CJK ideographs are one run of 20,992 -- so ranges make the table two orders of
magnitude smaller than the code-point count and a binary search over them is a handful of
comparisons. The generated file is checked in, because a build that downloads from unicode.org is a
build that fails when the network does and a build whose output depends on when it ran.

    tools/unicode/generate.py <ucd-directory> > src/text/UnicodeTables.inc

The UCD files are not vendored: they are large, they are versioned upstream, and the generated table
records which version produced it. Fetch them with:

    curl -O https://www.unicode.org/Public/15.1.0/ucd/LineBreak.txt
    curl -O https://www.unicode.org/Public/15.1.0/ucd/EastAsianWidth.txt
"""

import re
import sys
from pathlib import Path

# The line-break classes this browser distinguishes, and *only* those. UAX #14 defines around forty;
# collapsing the rest into AL (ordinary letter) is a deliberate simplification with a stated cost --
# see the header of src/text/LineBreak.h. Adding a class here is a one-line change plus a pair-table
# row, which is the shape a later session wants.
KEPT_CLASSES = {
    "BK", "CR", "LF", "NL",        # mandatory breaks
    "SP", "ZW", "WJ", "GL", "CM",  # spaces and joiners
    "BA", "HY", "B2",              # break-after, hyphen, break-either-side
    "OP", "CL", "CP", "QU",        # brackets and quotes
    "EX", "IS", "SY", "NS", "IN", "NU",  # punctuation, the solidus, and numbers
    "ID", "CJ", "H2", "H3", "JL", "JV", "JT",  # CJK and Hangul
    "PR", "PO",                    # prefix and postfix currency
    "AI", "AL", "SA",              # ambiguous, ordinary, complex-context
    "EB", "EM",                    # emoji base and modifier
}


def parse_ranges(path, keep):
    """The UCD's `start..end; VALUE` lines, as (first, last, value) with runs merged."""
    entries = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        codes, _, value = (part.strip() for part in line.partition(";"))
        if not value:
            continue
        value = value.split()[0]
        if keep is not None and value not in keep:
            value = keep_default
        if ".." in codes:
            first, last = (int(part, 16) for part in codes.split(".."))
        else:
            first = last = int(codes, 16)
        entries.append((first, last, value))
    entries.sort()
    # Merge adjacent runs of the same value. The UCD splits them by block, and unmerged they are three
    # times as many rows for no information.
    merged = []
    for first, last, value in entries:
        if merged and merged[-1][2] == value and merged[-1][1] + 1 == first:
            merged[-1] = (merged[-1][0], last, value)
        else:
            merged.append((first, last, value))
    return merged


def version_of(path):
    match = re.search(r"-(\d+\.\d+\.\d+)\.txt", path.read_text(encoding="utf-8")[:200])
    return match.group(1) if match else "unknown"


keep_default = "AL"

if len(sys.argv) != 2:
    sys.exit(__doc__)
ucd = Path(sys.argv[1])
line_break = parse_ranges(ucd / "LineBreak.txt", KEPT_CLASSES)
# East Asian Width: only W, F and H matter to a text layout engine -- wide, fullwidth and halfwidth --
# because they are the ones whose advance is not the font's business but the character's.
width = [
    (first, last, value)
    for first, last, value in parse_ranges(ucd / "EastAsianWidth.txt", None)
    if value in {"W", "F", "H"}
]

out = sys.stdout
out.write("// Generated by tools/unicode/generate.py from the Unicode Character Database.\n")
out.write("// DO NOT EDIT. Regenerate instead, and diff the result.\n")
out.write("//\n")
out.write("// LineBreak.txt version %s, EastAsianWidth.txt version %s.\n"
          % (version_of(ucd / "LineBreak.txt"), version_of(ucd / "EastAsianWidth.txt")))
out.write("//\n")
out.write("// %d line-break ranges and %d wide-width ranges, merged from %d and %d UCD lines. The\n"
          % (len(line_break), len(width), 3608, 2621))
out.write("// ranges are sorted and non-overlapping, which is what lets the lookup be a binary\n")
out.write("// search -- and what a test asserts, because a generator bug here is a silent one.\n\n")

out.write("constexpr LineBreakRange kLineBreakRanges[] = {\n")
for first, last, value in line_break:
    out.write("    {0x%X, 0x%X, LineBreakClass::%s},\n" % (first, last, value))
out.write("};\n\n")

out.write("constexpr WidthRange kWideRanges[] = {\n")
for first, last, value in width:
    out.write("    {0x%X, 0x%X, EastAsianWidth::%s},\n"
              % (first, last, {"W": "Wide", "F": "Fullwidth", "H": "Halfwidth"}[value]))
out.write("};\n")
