#!/usr/bin/env python3
"""Generates src/html/EncodingIndexes.inc from the WHATWG Encoding Standard's index files.

ADR 0025 §2, session 32. The same argument as tools/unicode/generate.py: these are 78,000 mappings
across four files, a transcription error in any of them is a character that decodes to the wrong
character with no way to notice, and a generated table is diffable against the version before it.

Flat arrays indexed by *pointer*, not sorted ranges, because these indexes are 70-100% dense -- a
range table would be almost one row per entry and a lookup would be a binary search where an array
index does. 0xFFFF marks a hole, which is what the Encoding Standard calls a null pointer.

    tools/unicode/generate_encodings.py <index-directory> > src/html/EncodingIndexes.inc

The index files are not vendored, for the reason the UCD files are not: they are large and versioned
upstream. Fetch them with:

    for f in index-jis0208 index-euc-kr index-big5 index-gb18030; do
      curl -O https://encoding.spec.whatwg.org/$f.txt
    done
"""

import re
import sys
from pathlib import Path

# Distinct per width, because 0xFFFF is a legitimate code point in a 32-bit table (U+FFFF is a
# noncharacter, but the standard's indexes are free to be sparse in ways this must not mistake).
HOLE = 0xFFFF
WIDE_HOLE = 0xFFFFFFFF


def read_index(path):
    """`pointer  0xCODE  # comment` lines, as a flat list with holes."""
    entries = {}
    identifier = "unknown"
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("#"):
            match = re.search(r"Identifier: ([0-9a-f]{16})", line)
            if match:
                identifier = match.group(1)
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        pointer = int(parts[0])
        code = int(parts[1], 16)
        entries[pointer] = code
    size = max(entries) + 1
    values = [entries.get(i, HOLE) for i in range(size)]
    # **Big5 maps above the BMP** -- pointer 947 is U+27267, a supplementary CJK ideograph -- so the
    # element type is chosen from the data rather than assumed to be 16 bits. This was written as an
    # assertion first ("none of these indexes has one") and the assertion fired, which is the whole
    # reason to write one: a uint16 table would have truncated that character to U+7267 silently, and
    # `曦` for `𧉧` is a wrong character rather than a missing one.
    wide = any(value != HOLE and value > 0xFFFF for value in values)
    return values, identifier, wide


if len(sys.argv) != 2:
    sys.exit(__doc__)
directory = Path(sys.argv[1])

out = sys.stdout
out.write("// Generated by tools/unicode/generate_encodings.py from the WHATWG Encoding Standard's\n")
out.write("// index files. DO NOT EDIT. Regenerate instead, and diff the result.\n//\n")

tables = []
for name, symbol in (("index-jis0208", "kJis0208"), ("index-euc-kr", "kEucKr"),
                     ("index-big5", "kBig5"), ("index-gb18030", "kGb18030")):
    values, identifier, wide = read_index(directory / (name + ".txt"))
    tables.append((symbol, values, name, identifier, wide))
    out.write("// %s: %d entries, identifier %s%s\n"
              % (name, len(values), identifier, ", above the BMP" if wide else ""))

out.write("//\n// A hole -- 0xFFFF in a 16-bit table, 0xFFFFFFFF in a 32-bit one -- is what the standard\n")
out.write("// calls a null pointer: that pointer maps to no character, and a decoder must produce\n")
out.write("// U+FFFD rather than index past it.\n\n")

for symbol, values, name, _, wide in tables:
    out.write("// %s. %s\n" % (name, "32 bits: this index maps above the BMP."
                               if wide else "16 bits is enough for every entry."))
    out.write("constexpr std::uint%d_t %s[] = {\n" % (32 if wide else 16, symbol))
    line = "   "
    for value in values:
        if wide:
            line += " 0x%X," % (WIDE_HOLE if value == HOLE else value)
        else:
            line += " 0x%04X," % value
        if len(line) > 96:
            out.write(line + "\n")
            line = "   "
    if line.strip():
        out.write(line + "\n")
    out.write("};\n\n")
