#pragma once

#include <string>
#include <vector>

namespace microbrowser::wpt {

enum class TestKind {
  // A page that loads testharness.js and reports subtests.
  Testharness,
  // A page with `<link rel=match|mismatch>`: render both, compare pixels.
  Reftest,
};

struct WptTest {
  // Root-relative, with the query string a variant adds: "dom/x.any.html?foo".
  std::string url_path;
  TestKind kind = TestKind::Testharness;
  // Reftests only. Root-relative path of the reference document.
  std::string reference;
  // `rel=mismatch`: the two must differ rather than match.
  bool reference_mismatch = false;
  // `<meta name=timeout content=long>` or `// META: timeout=long`.
  bool long_timeout = false;
};

// Walks the checkout and decides what each file is.
//
// Upstream answers this with MANIFEST.json, generated by `wpt manifest`, which
// is Python and takes minutes. This reads the files instead -- a test is a
// testharness test because it loads testharness.js, and a reftest because it
// has a `rel=match` link, both of which are visible in the first few kilobytes.
// `<meta name="variant">` on a plain HTML file is expanded the same way
// `// META: variant=` is on a generated `.any.js` -- one process per variant,
// because a 13,000-subtest page is a TIMEOUT rather than a measurement.
// The result is cached beside the checkout keyed by its revision and a
// manifest version, so a classification change in this file invalidates it.
//
// `prefixes` filters by root-relative path prefix; empty means everything.
std::vector<WptTest> EnumerateTests(const std::string& wpt_root,
                                    const std::vector<std::string>& prefixes,
                                    bool refresh_cache, std::string* error);

}  // namespace microbrowser::wpt
